apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    exposedAPIs:
    - id: TMF642
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - ackAlarm:
          - GET
          - GET /id
          - POST
        - alarm:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - clearAlarm:
          - GET
          - GET /id
          - POST
        - groupAlarm:
          - GET
          - GET /id
          - POST
        - unAckAlarm:
          - GET
          - GET /id
          - POST
        - unGroupAlarm:
          - GET
          - GET /id
          - POST
        - commentAlarm:
          - GET
          - GET /id
          - POST
      - version: 4
        resources:
        - alarm:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - ackAlarm:
          - GET
          - GET /id
          - POST
        - unAckAlarm:
          - GET
          - GET /id
          - POST
        - clearAlarm:
          - GET
          - GET /id
          - POST
        - commentAlarmlarm:
          - GET
          - GET /id
          - POST
        - groupAlarm:
          - GET
          - GET /id
          - POST
        - unGroupAlarm:
          - GET
          - GET /id
          - POST
    - id: TMF656
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - problemGroup:
          - POST
        - problemUngroup:
          - POST
        - serviceProblem:
          - GET
          - GET /id
          - POST
          - DELETE
      - version: 4
        resources:
        - serviceProblem:
          - GET
          - GET /id
          - POST
          - DELETE
        - problemGroup:
          - POST
        - problemUnGroup:
          - POST
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    publishedEvents:
    - id: TMF642
      name: Alarm Management API
      port: 80
      resources:
      - alarmCreateEvent
      - alarmAttributeValueChangeEvent
      - alarmStateChangeEvent
      - alarmDeleteEvent
      - ackAlarmsCreateEvent
      - ackAlarmsStateChangeEvent
      - unAckAlarmsCreateEvent
      - unAckAlarmsStateChangeEvent
      - clearAlarmsCreateEvent
      - clearAlarmsStateChangeEvent
      - commentAlarmsCreateEvent
      - commentAlarmsStateChangeEvent
      - groupAlarmsCreateEvent
      - groupAlarmsStateChangeEvent
      - unGroupAlarmsCreateEvent
      - unGroupAlarmsStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF642_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF701
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF701_Process_Management/5.0.0/swagger/TMF701-ProcessManagement-v5.0.0.oas.yaml
      apiType: openapi
    - id: TMF656
      name: ServiceProblemManagement
      port: 80
      resources:
      - problemAcknowledgementCreateEvent
      - problemAcknowledgementDeleteEvent
      - problemAcknowledgementStateChangeEvent
      - problemGroupCreateEvent
      - problemGroupDeleteEvent
      - problemGroupStateChangeEvent
      - problemUnacknowledgementCreateEvent
      - problemUnacknowledgementDeleteEvent
      - problemUnacknowledgementStateChangeEvent
      - problemUngroupCreateEvent
      - problemUngroupDeleteEvent
      - problemUngroupStateChangeEvent
      - serviceProblemAttributeValueChangeEvent
      - serviceProblemCreateEvent
      - serviceProblemDeleteEvent
      - serviceProblemInformationRequiredEvent
      - serviceProblemStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF656_v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - id: TMF633
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceCatalogCreateEvent
      - serviceCatalogChangeEvent
      - serviceCatalogDeleteEvent
      - serviceCategoryCreateEvent
      - serviceCategoryChangeEvent
      - serviceCategoryDeleteEvent
      - serviceCandidateCreateEvent
      - serviceCandidateChangeEvent
      - serviceCandidateDeleteEvent
      - serviceSpecificationCreateEvent
      - serviceSpecificationChangeEvent
      - serviceSpecificationDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF633_v4.0.0.swagger.json
    - id: TMF638
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceChangeEvent
      - serviceDeleteEvent
      - serviceStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF638_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF639
      name: ResourceInventoryManagement
      port: 80
      resources:
      - resourceCreateEvent
      - resourceChangeEvent
      - resourceDeleteEvent
      - resourceStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF639_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF673
      name: API Place - GeographicAddress
      port: 80
      resources:
      - geographicAddressValidationStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF674
      name: GeographicSiteManagement
      port: 80
      resources:
      - geographicSiteCreateEvent
      - geographicSiteAttributeValueChangeEvent
      - geographicSiteStatusChangeEvent
      - geographicSiteDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF675
      name: GeographicLocationManagement
      port: 80
      resources:
      - geographicLocationCreateEvent
      - geographicLocationAttributeValueChangeEvent
      - geographicLocationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF675_GeographicLocation/blob/master/TMF675-GeographicLocation-v4.0.0.swagger.json
      apiType: openapi
    - id: TMF642
      name: AlarmManagement
      port: 80
      resources:
      - alarmCreateEvent
      - alarmAttributeValueChangeEvent
      - alarmStateChangeEvent
      - alarmDeleteEvent
      - ackAlarmsCreateEvent
      - ackAlarmsStateChangeEvent
      - unAckAlarmsCreateEvent
      - unAckAlarmsStateChangeEvent
      - clearAlarmsCreateEvent
      - clearAlarmsStateChangeEvent
      - commentAlarmsCreateEvent
      - commentAlarmsStateChangeEvent
      - groupAlarmsCreateEvent
      - groupAlarmsStateChangeEvent
      - unGroupAlarmsCreateEvent
      - unGroupAlarmsStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF642_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF656
      name: ServiceProblemManagement
      port: 80
      resources:
      - problemAcknowledgementCreateEvent
      - problemAcknowledgementDeleteEvent
      - problemAcknowledgementStateChangeEvent
      - problemGroupCreateEvent
      - problemGroupDeleteEvent
      - problemGroupStateChangeEvent
      - problemUnacknowledgementCreateEvent
      - problemUnacknowledgementDeleteEvent
      - problemUnacknowledgementStateChangeEvent
      - problemUngroupCreateEvent
      - problemUngroupDeleteEvent
      - problemUngroupStateChangeEvent
      - serviceProblemAttributeValueChangeEvent
      - serviceProblemCreateEvent
      - serviceProblemDeleteEvent
      - serviceProblemInformationRequiredEvent
      - serviceProblemStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF656_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF621
      name: TroubleTicketManagement
      port: 80
      resources:
      - troubleTicketCreateEvent
      - troubleTicketAttributeValueChangeEvent
      - troubleTicketStatusChangeEvent
      - troubleTicketDeleteEvent
      - troubleTicketResolvedEvent
      - troubleTicketInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF621_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF632
      name: PartyManagement
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF669
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF662
      name: EntityCatalogManagement
      port: 80
      resources:
      - entityCatalogCreateEvent
      - entityCatalogDeleteEvent
      - entityCatalogItemCreateEvent
      - entityCatalogItemDeleteEvent
      - entitySpecificationCreateEvent
      - entitySpecificationDeleteEvent
      - associationSpecificationCreateEvent
      - associationSpecificationDeleteEvent
      - associationCreateEvent
      - associationDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF662_v4.0.0.swagger.json
      apiType: openapi
  componentMetadata:
    id: TMFC043
    name: FaultManagement
    version: 1.1.0
    description: Fault Management component involves identifying, diagnosing, and resolving issues that prevent the communication resources and their overlaying services from functioning correctly. Its scope covers this functionality at the ODA Production layer while business related resolutions are not part of its scope. The Fault Management component manages the currently active alarms or problem candidates, potentially modifying or enhancing their data to make persistent alarms more actionable. It may apply logic to preserve alarms that reflect actual problems, eliminating those that are merely symptoms. Various actions can be taken using the alarm/problem information as part of the resolution process, such as applying automated/automonous corrective actions or opening trouble tickets.
    publicationDate: '2026-05-21'
    status: production
    functionalBlock: Production
    owners:
    - name: Redacted
      email: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.5.8|Resource_Trouble_Management|v25.0
    - 1.4.6|Service_Problem_Management|v25.0
    functionalFrameworkFunctions:
    - 1187|Resource_Trouble_Resolution|v25.0
    - 615|Service_Problem_Tracking_&_Management|v25.0
    - 1155|Resource_Diagnostic_and_Test_Analysis|v25.0
    - 1186|Resource_Trouble_Cause_Identification|v25.0
    - 610|Service_Problem_Prioritization|v25.0
    - 612|Service_Problem_Automatic_Correction|v25.0
    - 979|Service_Assurance_Control_Calculation|v25.0
    - 980|Service_Assurance_Trouble_Mitigation|v25.0
    - 1067|Service_Problem_Manual_Correction_Support|v25.0
    SIDs:
    - Resource_Domain|Resource_Trouble_ABE|Resource_Alarm_ABE|v25.0
    - Resource_Domain|Resource_Trouble_ABE|AlarmSeverityAssignmentProfile_BE|v25.0
    - Service_Domain|Service_Problem_ABE|v25.0
