apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: PartyManagement
  id: TMFC028
  functionalBlock: PartyManagement
  description: 'Party Management component is responsible for the capture, validation
    and management of Parties and their Roles. A Party may be an individual or organization
    that has a relationship with an enterprise. In this context it is responsible
    for the e2e life cycle of: Individual, Organization. and its related sub-entities:Contact
    Medium, Currency and tax exemption certificates, Identification, Community'
  publicationDate: 2024-10-14 00:00:00
  status: specified
  version: 2.1.0
  coreFunction:
    dependentAPIs:
    - id: TMF669
      required: true
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      version: 4        
    - id: TMF674     
      required: false        
      resources:
      - geographicSite:
        - GET
        - GET /id          
      version: 4
    - id: TMF675      
      required: false
      resources: 
      - geographicLocation:
        - GET
        - GET /id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    - id: TMF688
      required: false
      resources:
      - event:
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - id: TMF632
      required: true
      resources:
      - individual:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - organization:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET/id
        - POST
        - DELETE/id
      - taskFlow:
        - GET
        - GET/id
        - PATCH/id
      version: 4
    publishedEvents:     
    - apiType: openapi
      implementation: /{{.Release.Name}}-partymngtapi
      name: Party Management API
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json     
    subscribedEvents: []
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
