apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: PartyManagement
  id: TMFC028
  functionalBlock: PartyManagement
  description: 'Party Management component is responsible for the capture, validation
    and management of Parties and their Roles. A Party may be an individual or organization
    that has a relationship with an enterprise. In this context it is responsible
    for the e2e life cycle of: Individual, Organization. and its related sub-entities:Contact
    Medium, Currency and tax exemption certificates, Identification, Community'
  publicationDate: 2024-10-14 00:00:00
  status: specified
  version: 2.1.0
  coreFunction:
    dependentAPIs:
    - id: TMF669
      required: true
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      version: 4        
    - id: TMF674     
      required: false        
      resources:
      - geographicSite:
        - GET
        - GET /id          
      version: 4
    - id: TMF675      
      required: false
      resources: 
      - geographicLocation:
        - GET
        - GET /id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    - id: TMF688
      required: false
      resources:
      - event:
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - id: TMF632
      required: true
      resources:
      - individual:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - organization:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET/id
        - POST
        - DELETE/id
      - taskFlow:
        - GET
        - GET/id
        - PATCH/id
      version: 4
    publishedEvents:     
    - apiType: openapi
      implementation: /{{.Release.Name}}-partymngtapi
      name: Party Management API
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json     
    subscribedEvents: []
  owners:
  - email: Redacted
    name: Redacted
  maintainers:
  - name: Redacted
    email: components@tmforum.org
  eTOMs:
  - 1.3.16_Customer_Inventory_Management_v23.0
  - 1.3.6_Customer_Information_Management_v23.0
  - 1.3.4_Customer_Relationship_Management_v23.0
  - 1.3.4.2_Establish_Customer_Relationship_v23.0
  - 1.3.4.3_Re-establish_Customer_Relationship_v23.0
  - 1.3.4.4_Terminate_Customer_Relationship_v23.0
  - 1.6.3_Party_Relationship_Development_&_Retirement_v23.0
  - 1.6.3.1_Party_Relationship_Management_v23.0
  - 1.6.3.1.5_Collect_Party_data_v23.0
  - 1.6.21_Party_Inventory_Management_v23.0
  - 1.7.7_Human_Resources_Management_v23.0
  - 1.7.7.2_Develop_the_Workforce_v23.0
  functionalFrameworkFunctions:
  - 92_Customer_Relation_Map_Exposure_v23.0
  - 369_Customer_Data_Fencing_v23.0
  - 225_Customer_Details_Management_v23.0
  - 400_Customer_Information_Management_v23.0
  - 282_Customer_Information_Presentation_v23.0
  - 226_Customer_Preferences_Administration_v23.0
  - 364_Customer/Prospect_Data_Acquisition_v23.0
  - 233_Customer_Actions_Profile_Updating_v23.0
  - 195_Customers_Hierarchy_and_Group_Management_v23.0
  - 122_Customer_Information_Searching_v23.0
  - 91_Customer_Profile_Updating_v23.0
  - 121_Registration_v23.0
  - 124_Guided_Customer_Information_Capturing_v23.0
  - 1032_Partner_Group_and_Hierarchy_Definition_v23.0
  - 1033_Partner_Group_and_Hierarchy_Assigning_v23.0
  - 1035_Partner_Preferences_Management_v23.0
  - 1034_Partner_Profile_Management_v23.0
  - 1036_Partner_Profile_Enquiry_and_Filtering_v23.0
  - 1037_Partner_Profile_Storage_v23.0
  - 746_Partner_Workflow_Management_v23.0
