apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs: []
    exposedAPIs:
    - id: <TMFnnn>
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - <resourceName>:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    publishedEvents: []
    subscribedEvents: []
  componentMetadata:
    id: TMFC000
    name: ComponentName
    version: <n.n.n>
    description: <One-paragraph statement of what the component is responsible for.>
    publicationDate: <YYYY-MM-DD>
    status: <production | roadmap | preview>
    functionalBlock: <CoreCommerce | Production | PartyManagement | IntelligenceManagement>
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
    SIDs: []
