apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: 4
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF669
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: 4
        resources:
        - partyRole:
          - GET
          - GET /id
    - id: TMF646
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - appointment:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - searchTimeSlot:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - GET
          - GET /id
          - POST
          - DELETE
        - taskFlow:
          - GET
          - GET /id
          - PATCH
    - id: TMF688
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - event:
          - GET
          - GET /id
    exposedAPIs:
    - id: TMF713
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - work:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - workSpecification:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF697
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - workOrder:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - cancelWorkOrder:
          - GET
          - GET /id
          - POST
    - id: TMF714
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - checkWorkQualification:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE
        - queryWorkQualification:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
    - id: TMF701
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - processFlow:
          - GET
          - GET /id
          - POST
          - DELETE
        - taskFlow:
          - GET
          - GET /id
          - PATCH /id
    - id: TMF688
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - listener:
          - POST
          - DELETE
        - hub:
          - POST
          - DELETE
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/workManagement/hub
      name: TMF713 Work Management API
      port: 80
      resources:
      - workStateChange
      - workCreateEvent
      - workAttributeValueChangeEvent
      - workDeleteEvent
      - workSpecificationsearchTimeSlotCreateEvent
      - workSpecificationAttributeValueChangeEvent
      - workSpecificationStateChangeEvent
      - workSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF713_WorkManagement/blob/master/TMF713-Work-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/WorkOrderManagementEvent/hub
      name: TMF697_WorkOrderManagement
      port: 80
      resources:
      - workOrderStateChange
      - workOrderCreateEvent
      - workOrderAttributeValueChangeEvent
      - workOrderDeleteEvent
      - workOrderInformationRequiredEvent
      - cancelWorkOrderCreateEvent
      - cancelWorkOrderStateChangeEvent
      - cancelWorkOrderDeleteEvent
      specification: https://github.com/tmforum-apis/TMF697_WorkOrderManagement/blob/master/TMF97-WorkOrder-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/WorkQualificationManagementEvent/hub
      name: workQualificationManagement
      port: 80
      resources:
      - checkWorkQualificationStateChange
      - checkWorkQualificationCreateEvent
      - checkWorkQualificationAttributeValueChangeEvent
      - checkWorkQualificationtDeleteEvent
      - checkWorkQualificationInformationRequiredEvent
      - queryWorkQualificationStateChangeEvent
      - queryWorkQualificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF714_WorkQualificationManagement/blob/master/TMF714-WorkQualification-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF701_Process_Management/5.0.0/swagger/TMF701-ProcessManagement-v5.0.0.oas.yaml
      apiType: openapi
    subscribedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
      name: PartyManagement
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourcePoolManagement/hub
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF701_Process_Management/5.0.0/swagger/TMF701-ProcessManagement-v5.0.0.oas.yaml
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AppointmentManagementEvent/hub
      name: appointmentManagement
      port: 80
      resources:
      - appointmentStateChange
      - appointmentCreateEvent
      - appointmentAttributeValueChangeEvent
      - appointmentDeleteEvent
      - searchTimeSlotCreateEvent
      - searchTimeSlotAttributeValueChangeEvent
      - searchTimeSlotStateChangeEvent
      - searchTimeSlotDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF646_v4.0.0.swagger.json
      apiType: openapi
  componentVersion: 1.1.0
  componentMetadata:
    id: TMFC061
    name: WorkOrderManagement
    version: 1.1.0
    description: Work Order Management component is responsible of the setup and maintenance requests from initiation to completion.Work Order is a formal request that outlines essential details related to necessary setup/maintenance tasks. These details typically include Nature of the task A description of the work that needs to be done. Location Where the maintenance or repair is required. Required materials The items or resources needed for the job. Assigned personnel The technician or contractor responsible for executing the work. Timeline for completion The expected timeframe within which the task should be finished.
    publicationDate: 2024-06-25
    status: roadmap
    functionalBlock: Production
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.5.5|Resource_Order_Management|v23.5
    - 1.5.5.7|Manage_Resource_Work_Order|v23.5
    - 1.5.19|Resource_Specification_Management|v23.5
    - 1.5.19.1|Develop_Resource_Specifications|v23.5
    - 1.5.19.2|Master_Resource_Specifications|v23.5
    - 1.5.19.3|Analyze_Resource_Specifications|v23.5
    - 1.5.19.4|Update_and_Version_Resource_Specifications|v23.5
    functionalFrameworkFunctions:
    - 542|Dynamic_Work_Order_Assigning|v23.5
    - 543|Periodic_Bulk_Work_Order_Assigning|v23.5
    - 545|Work_Order_Coordination|v23.5
    - 547|Work_Order_Information_Transferring|v23.5
    - 549|Work_Order_Re-assigning|v23.5
    - 540|Work_Order_Manual_Activities_Determining|v23.5
    - 544|Work_Order_Closing|v23.5
    - 739|Workflow_Delay_Jeopardy_Analyzing|v23.5
    - 551|Work_Order_Status_Monitoring|v23.5
    - 553|Work_Specification_Classification|v23.5
    - 541|Work_Order_Assignment_Dispatching|v23.5
    - 548|Work_Orders_Initiation|v23.5
    - 552|Work_Order_Updating|v23.5
    SIDs:
    - Enterprise_Domain|Workforce_ABE|Work_Specification_ABE|v25.0
    - Product_Domain|Project_ABE|Work_Order_ABE|v25.0
