apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    exposedAPIs:
    - id: TMF673
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - geographicAddressValidation:
          - GET
          - GET /id
          - POST
          - PATCH
        - geographicAddress:
          - GET
          - GET /id
        - geographicSubAddress:
          - GET
          - GET /id
    - id: TMF674
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - geographicSite:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF675
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - geographicLocation:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    publishedEvents:
    - id: TMF673
      name: API Place - GeographicAddress
      resources:
      - geographicAddressValidationStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF673_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF674
      name: GeographicSiteManagement
      resources:
      - geographicSiteAttributeValueChangeEvent
      - geographicSiteCreateEvent
      - geographicSiteDeleteEvent
      - geographicSiteStatusChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF674_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF675
      name: GeographicLocation
      resources:
      - geographicLocationAttributeValueChangeEvent
      - geographicLocationCreateEvent
      - geographicLocationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents: []
  componentMetadata:
    id: TMFC014
    name: LocationManagement
    version: 1.3.1
    description: The Location Management component allows easy reference to geographic places important to other entities, where a geographic place is an entity that can answer the question "where?" This component could be a facade tool for GIS systems, address sytems, BIM systems, mapping systems ... (eg. Google Maps).
    publicationDate: 2023-08-18
    status: roadmap
    functionalBlock: Production
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions:
    - 429|Location_Change_History_Management|v23.0
    - 430|PreFormattedLocation_InformationPresentation|v23.0
    - 431|Location_Information_Updating|v23.0
    - 432|Location_Information_Searching|v23.0
    - 433|Location_Structure_Data_Configuration|v23.0
    - 434|Location_Data_Integrity_Management|v23.0
    SIDs:
    - Shared_Domain|Location_ABE|Geographic_Place_ABE|v23.5
    - Shared_Domain|Location_ABE|Geographic_Location_ABE|v23.5
    - Shared_Domain|Location_ABE|Geographic_Address_ABE|v23.5
    - Shared_Domain|Location_ABE|Geographic_Site_ABE|v23.5
    - Shared_Domain|Location_ABE|Local_Place_ABE|v23.5
