apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  id: TMFC007
  name: ServiceOrderManagement
  functionalBlock: Production 
  description: "The SOM is the entry point of the Production Domain. It oversees Customer-Facing-Service (CFS) delivery of resources (network and service platforms equipment). The SOM exposes in particular the API ServiceOrder. It is triggered when the Product Order Orchestration Management component calls this API to request CFS delivery. To achieve delivery of a CFS, the SOM orchestrates the CFS delivery process which. Identifies possible RFS and chooses one, using the catalog and technical inventory. Selects the resources (servers, equipment, etc.) and their instances. Requests the ROM to update selected resource instances to deliver CFS. Request sent to the ROM contain the CFS and the list of configured resource instances to update."
  version: 1.1.1
  status: specified 
  publicationDate: 2024-02-23
  maintainers:
    - name: Gaetano Biancardi
      email: gaetano.biancardi@accenture.com
    - name: Sylvie Demarest
      email: sylvie.demarest@orange.com
  owners: 
    - name: Gaetano Biancardi
      email: gaetano.biancardi@accenture.com
    - name: Sylvie Demarest
      email: sylvie.demarest@orange.com    
  coreFunction:
    exposedAPIs:
      - name: TMF641 Service Ordering Management API
        id: TMF641
        required: true
        version: 4.1
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
        implementation: '/{{.Release.Name}}-serviceOrdeManagement'
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrdeManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrdeManagement/v4/docs
        port: 8080
        resources:
          - serviceOrder:
            - GET
            - GET /id
            - POST
            - PATCH
            - DELETE
          - cancelServiceOrder:
            - GET
            - GET /id
            - POST
      - name: ProcessFlowManagement
        id: TMF701
        required: false
        version: 4.0
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
        implementation: /{{.Release.Name}}-procmngttapi
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
        port: 8080
        resources:
          - processFlow:
              - GET
              - GET /id
              - POST
              - DELETE /id
          - taskFlow:
              - GET
              - GET /id
              - PATCH /id
      - name: Event
        id: TMF688
        required: false
        version: 4.0
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
        implementation: '/{{.Release.Name}}-PromotionManagement'
        apitype: openapi
        path: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
        developerUI: >-
          /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
        port: 8080
        resources:
          - listener:
            - POST
          - hub:
            - POST
            - DELETE /id
    dependentAPIs:
      - name: TMF632 Party Management API
        id: TMF632
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
          - individual:
            - GET
            - GET /id
          - organization:
            - GET
            - GET /id    
      - name: TMF633 Service Catalog Management API
        id: TMF633
        required: true
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - serviceSpecification:
          - GET
          - GET /id
      - name: TMF634 Resource Catalog Management API
        id: TMF634
        required: true
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF652_Resource_Order_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - resourceSpecification:
          - GET
          - GET /id              
      - name: TMF638 Service Inventory Management API
        id: TMF638
        required: true
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - service:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
      - name: TMF639 Resource Inventory Management API
        id: TMF639
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - resource:
          - GET
          - GET /id              
      - name: TMF640 Service Activation Management API
        id: TMF640
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF640_Service_Activation_Management_API_v4.0.0_swagger.json
        apitype: openapi
        port: 8080
        resources:
        - monitor:
          - GET
          - GET /id
      - name: TMF641 Service Ordering Management API
        id: TMF641
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
        apitype: openapi
        port: 8080
        resources:
        - serviceOrder:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - cancelServiceOrder:
          - GET
          - GET /id
          - POST
      - name: TMF645 Service Qualification Management API
        id: TMF645
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - checkServiceQualification:
          - GET
          - GET /id
          - POST
          - PATCH
        - queryServiceQualification:
          - GET
          - GET /id
          - POST
          - PATCH
      - name: TMF646 Appointment Management API
        id: TMF646
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF646_Appointment_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - appointment:
          - GET
          - GET /id
          - POST
          - PATCH
        - searchTimeSlot:
          - GET
          - GET /id
          - POST
          - PATCH
      - name: TMF652 Resource Order Management API 
        id: TMF652
        required: true
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
        apitype: openapi
        resources:
        - resourceOrder:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - cancelResourceOrder:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE                        
      - name: TMF653 Service Test Management API
        id: TMF653
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.2.0/swagger/TMF653_Service_Test_Management_API_v4.2.0_swagger.json
        apitype: openapi
        resources:
        - serviceTest:
          - GET
          - GET /id
        - serviceTestSpecification:
          - GET
          - GET /id        
      - name: TMF672 User Role Permission Management API
        id: TMF672
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
        - permission:
          - GET
          - GET /id         
      - name: TMF669 Party Role Management API
        id: TMF669
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
          - PartyRole:
              - GET
              - GET /id       
      - name: TMF673 Geographic Address Management API
        id: TMF673
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
          - geographicAddress:
              - GET
              - GET /id
          - geographicSubAddress:
              - GET
              - GET /id
          - geographicAddressValidation:
              - GET
              - GET /id
              - POST       
      - name: TMF674 Geographic Site Management API
        id: TMF674
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
          - geographicSite:
              - GET
              - GET /id         
      - name: TMF681 Communication Management API
        id: TMF681
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF681_Communication_Management_API_v4.0.0_swagger.json
        apitype: openapi
        resources:
          - communicationMessage:
              - GET
              - GET /id              
      - name: Resource Pool Management API
        id: TMF685
        required: false
        version: 4.0
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/Historic/3.0.0/swagger/TMF685-ResourcePool-v3.0.0.admin.swagger.json
        apitype: openapi
        resources:
          - reservation:
              - GET
              - GET /id  
              - POST
              - PATCH
              - DELETE          
          - resourcePool:
              - GET
              - GET /id                                                      
      - name: Event
        id: TMF688
        required: false
        version: 4.0
        specification: >-
          https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
        apitype: openapi
        resources:
          - event:
              - GET
              - GET /id
      - name: ProcessFlowManagement
        id: TMF701
        required: false
        version: 4.0
        specification: >-
          https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
        apitype: openapi
        resources:
          - processFlow:
              - POST
              - GET
              - GET /id
              - PATCH
                
    publishedEvents:
      - name: TMF641 Service Ordering Management API
        specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
        hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrdeManagement/hub
        apitype: openapi
        port: 80
        resources:
        - serviceOrderCreateEvent
        - serviceOrderStateChangeEvent
        - serviceOrderDeleteEvent
        - serviceOrderAttributeValueChangeEvent
        - serviceOrderInformationRequiredEvent
        - serviceOrderMilestoneEvent
        - serviceOrderJeopardyEvent
        - cancelServiceOrderCreateEvent
        - cancelServiceOrderStateChangeEvent
        - cancelServiceOrderInformationRequiredEvent
    subscribedEvents: []        


