apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF633
      required: false
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF669
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organisation:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF634
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      version: 4.1
      apiSDO: tmForum
    - id: TMF651
      required: false
      resources:
      - agreement:
        - GET
        - GET /id
      - agreementSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF675
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF662
      required: false
      resources:
      - entitySpecification:
        - GET
        - GET /id
      - associationSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF620
      required: false
      resources:
      - catalog:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - category:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOffering:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOfferingPrice:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - importJob:
        - GET
        - GET /id
        - POST
        - DELETE
      - exportJob:
        - GET
        - GET /id
        - POST
        - DELETE
      version: 4
      apiSDO: tmForum
    exposedAPIs:
    - id: TMF620
      required: true
      resources:
      - catalog:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - category:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOffering:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOfferingPrice:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - exportJob:
        - POST
        - GET
        - GET /id
        - DELETE
      - importJob:
        - POST
        - GET
        - GET /id
        - DELETE
      version: 4
      apiSDO: tmForum
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF671
      required: false
      resources:
      - promotion:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
      apiSDO: tmForum
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productspecification/hub
      implementation: /{{.Release.Name}}-ProductCatalogManagementEvent
      name: ProductCatalogManagement
      port: 80
      resources:
      - productSpecificationCreate
      - productSpecificationDeleteEvent
      - categoryCreateEvent
      - categoryDeleteEvent
      - productOfferingCreateEvent
      - productOfferingAttributeValueChangeEvent
      - productOfferingStateChangeEvent
      - productOfferingDeleteEvent
      - productOfferingPriceCreateEvent
      - productOfferingPriceAttributeValueChangeEvent
      - productOfferingPriceStateChangeEvent
      - productOfferingPriceDeleteEvent
      - catalogCreateEvent
      - catalogDeleteEvent
      - catalogBatchEvent
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagementEvent/hub
      implementation: /{{.Release.Name}}-PromotionManagementEvent
      name: PromotionManagement
      port: 80
      resources:
      - promotionCreateEvent
      - promotionDeleteEvent
      - promotionAttributeValueChangeEvent
      - promotionStateChangeEvent
      - promotionInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF671_Promotion/blob/master/TMF671-Promotion-v4.1.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationStateChange
      - serviceSpecificationAttributeValueChangeEvent
      - serviceSpecificationCreateEvent
      - serviceSpecificationDeleteEvent
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
      specification: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-Party
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
      apiType: openapi
  componentMetadata:
    id: TMFC001
    name: ProductCatalogManagementXXX
    version: 2.1.0
    description: The product catalog management component is responsible for organizing the collection of products and product offering specifications that identify and define all requirements of a product or a product offering that can be commercialized.
    publicationDate: 2024-11-12 00:00:00
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.2.20-Product_Catalog_Lifecycle_Management-v23.5
    - 1.1.19-Loyalty_Program_Management-v23.5
    - 1.1.19.1-Loyalty_Program_Development_&_Retirement-v23.5
    - 1.2.7-Product_Specification_&_Offering_Development_&_Retirement-v23.5
    - 1.2.8.7-Implement_Product_Capacity_Plan-v23.5
    - 1.6.4-Business_Partner_Offering_Development_&_Retirement-v23.5
    - 1.2.8-Product_Capacity_Management-v23.5
    - 1.2.22-Product_Catalog_Content_Management-v23.5
    - 1.2.21-Product_Catalog_Operational_Readiness_Management-v23.5
    - 1.2.19-Product_Catalog_Planning_Management-v23.5
    - 1.2.23-Product_Specification_Management-v23.5
    - 1.2.8.7.1-Specify_Required_Product_Capacity-v23.5
    functionalFrameworkFunctions:
    - 3-Repository_Entity_Relations_Configuration-v23.5
    - 4-Repository_Entity_Grouping_Configuration-v23.5
    - 6-Repository_Entity_Data_Model_Configuration-v23.5
    - 11-Repository_Entity_Hierarchy_Management-v23.5
    - 123-Product_Catalog_Browsing-v23.5
    - 210-Centralized_Ordering_Rules_Management-v23.5
    - 238-Customer_Loyalty_Rules_Management-v23.5
    - 263-Product_Compatibility_Checking-v23.5
    - 360-Product_Agreement_Specification_Design-v23.5
    - 407-Product_Modeling_Support-v23.5
    - 408-Product_Retirement-v23.5
    - 415-Product_Strategy_linking-v23.5
    - 649-Product_Sourcing_Registration-v23.5
    - 650-Partner_Product_Certification-v23.5
    - 662-Sourcing_Reference_Data_Collection-v23.5
    - 721-Customer_Order_Rules_Configuration-v23.5
    - 722-Order_Rules_Retrieval-v23.5
    - 992-Entity_Management_Notification-v23.5
    - 993-Entity_Management_Reporting-v23.5
    - 1050-Product_Onboarding_Management-v23.5
    - 1053-Onboarded_Product_Workflows_Definition-v23.5
    - 1076-Product_Specification_Design-v23.5
    - 1077-Product_Offering_Design-v23.5
    - 1078-Product_Specification_and_Offering_Change_Auditing-v23.5
    - 1079-Product_Specification_and_Offering_Repository_Management-v23.5
    - 416-Product_Propositions_Operations_Planning-v23.5
    - 417-Product_Strategy_to_Proposition_Alignment-v23.5
    - 418-Product_Strategy/Propositions_Creation-v23.5
    - 419-Product_Strategy_performance_reporting-v23.5
    - 897-Building_Access_Control-v23.5
    - 900-Authorization_Control_Management-v23.5
