apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF633
      required: false
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF669
      required: false
      resources:
      - PartyRole:
        - GET
        - GET /id
      version: 4
    - id: TMF632
      required: false
      resources:
      - Individual:
        - GET
        - GET /id
      - Organisation:
        - GET
        - GET /id
      version: 4
    - id: TMF634
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF651
      required: false
      resources:
      - agreement:
        - GET
        - GET /id
      - agreementSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF623
      required: false
      resources:
      - serviceLevelAgreement:
        - GET
        - GET /id
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      version: 4
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
    - id: TMF675
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      version: 4
    - id: TMF672
      required: false
      resources:
      - permission:
        - GET
        - GET /id
      version: 4
    - id: TMF662
      required: false
      resources:
      - entitySpecification:
        - GET
        - GET /id
      - associationSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF620
      required: false
      resources:
      - catalog:
        - GET
        - GET /id
      - category:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOffering:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - ProductOfferingPrice:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - importJob:
        - GET
        - POST
        - DELETE
      - exportJob:
        - GET
        - POST
        - DELETE
      version: 4
    - id: TMF688
      required: false
      resources:
      - event:
        - POST
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productCatalogManagement/v4/docs
      id: TMF620
      implementation: /{{.Release.Name}}-prodcatapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productCatalogManagement/v4
      port: 8080
      required: true
      resources:
      - catalog:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - category:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOffering:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productOfferingPrice:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - exportJob:
        - POST
        - GET
        - GET /id
        - DELETE
      - importJob:
        - POST
        - GET
        - GET /id
        - DELETE
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      port: 8080
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      id: TMF671
      implementation: /{{.Release.Name}}-PromotionManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      port: 8080
      required: false
      resources:
      - promotion:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-PromotionManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      port: 8080
      required: false
      resources:
      - listener:
        - POST
      - hub:
        - POST
        - DELETE
      version: 4
    publishedEvents:
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productspecification/hub
      implementation: /{{.Release.Name}}-ProductCatalogManagementEvent
      name: ProductCatalogManagement
      port: 80
      resources:
      - productSpecificationCreate
      - productSpecificationDeleteEvent
      - categoryCreateEvent
      - categoryDeleteEvent
      - productOfferingCreateEvent
      - productOfferingAttributeValueChangeEvent
      - productOfferingStateChangeEvent
      - productOfferingDeleteEvent
      - productOfferingPriceCreateEvent
      - productOfferingPriceAttributeValueChangeEvent
      - productOfferingPriceStateChangeEvent
      - productOfferingPriceDeleteEvent
      - catalogCreateEvent
      - catalogDeleteEvent
      - catalogBatchEvent
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagementEvent/hub
      implementation: /{{.Release.Name}}-PromotionManagementEvent
      name: PromotionManagement
      port: 80
      resources:
      - promotionCreateEvent
      - promotionDeleteEvent
      - promotionAttributeValueChangeEvent
      - promotionStateChangeEvent
      - promotionInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF671_Promotion/blob/master/TMF671-Promotion-v4.1.0.swagger.json
    - apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationStateChange
      - serviceSpecificationAttributeValueChangeEvent
      - serviceSpecificationCreateEvent
      - serviceSpecificationDeleteEvent
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
      specification: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-UserRolePermission
      name: UserRolePermission
      port: 80
      resources:
      - permissionDeleteEvent
      specification: https://github.com/tmforum-apis/TMF672_UserRolesPermissions/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      implementation: /{{.Release.Name}}-Party
      name: Party
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
  description: The Product Catalog Management ODA Component is responsible for organizing
    the collection of Products and Product Offerings specifications that identify
    and define all requirements of a product or a product offering that can be commercialized.
  functionalBlock: CoreCommerce
  id: TMFC001
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  name: ProductCatalogManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: 2023-08-18 00:00:00
  status: specified
  version: 1.2.1
