apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: AgreementManagement
  id: TMFC039
  functionalBlock: CoreCommerce
  description: Agreement Management component is responsible for creating, storing,
    editing, and tracking agreed  arrangements with related terms and conditions over
    a lifecycle. The component manages offers, records acceptance, and associated
    considerations and intentions to establish agreements as legally binding. As well
    this components provides workfows and templates that facilitates collaboration,
    communication and negotiation of agreements between parties, and administers the
    specificities related to translate  agreements into contracts, when it is required.
    It provides a secure storage, version control, compliance management, and renewal
    notifications for agreements.
  publicationDate: 2024-08-19 00:00:00
  status: specified
  version: 1.1.0
  coreFunction:
    dependentAPIs:
    - id: TMF632
      required: true
      resources:
      - individual:
        - GET
        - GET/id
      - organization:
        - GET
        - GET/id
      version: 4
    - id: TMF669
      required: false
      resources:
      - partyRole:
        - GET
        - GET/id
      version: 4
    - id: TMF620
      required: false
      resources:
      - productOffering:
        - GET
        - GET/id
      - productOfferingPrice:
        - GET
        - GET/id
      version: 4
    - id: TMF637
      required: false
      resources:
      - product:
        - GET
        - GET/id
      version: 4
    - id: TMF667
      required: false
      resources:
      - document:
        - GET
        - GET/id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - id: TMF651
      required: true
      resources:
      - agreement:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - agreementSpecification:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    publishedEvents:
    - implementation: /{{.Release.Name}}-agreemngtapi
      name: userRole
      port: 80
      resources:
      - agreementCreateEvent
      - agreementAttributeValueChangeEvent
      - agreementStateChangeEvent
      - agreementSpecificationCreateEvent
      - agreementSpecificationAttributeValueChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF651_AgreementManagement/master/TMF651-AgreementManagement-v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      apiType: openapi
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
