apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF634
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - resourceSpecification:
          - GET
          - GET /id
      - version: 4
        resources:
        - resourceSpecification:
          - GET
          - GET /id
    - id: TMF639
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - resource:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
    exposedAPIs:
    - id: TMF702
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - resource:
          - GET
          - GET /id
          - POST /id
          - PATCH
          - DELETE /id
    - id: TMF664
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - resourceFunction:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - heal:
          - GET
          - GET /id
          - POST
        - scale:
          - GET
          - GET /id
          - POST
        - migrate:
          - GET
          - GET /id
          - POST
    publishedEvents:
    - id: TMF702
      apitype: openapi
      name: API Resource Activation and Configuration
      resources:
      - ResourceCreateEvent
      - ResourceAttributeValueChangeEvent
      - ResourceStateChangeEvent
      - ResourceDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF702_v4.0.0.swagger.json
    - id: TMF664
      apitype: openapi
      name: Resource Function Activation and Configuration
      resources:
      - ResourceFunctionCreateEvent
      - ResourceFunctionAttributeValueChangeEvent
      - ResourceFunctionChangeEvent
      - ResourceFunctionDeleteEvent
      - HealCreateEvent
      - HealAttributeValueChangeEvent
      - HealChangeEvent
      - HealDeleteEvent
      - ScaleCreateEvent
      - ScaleAttributeValueChangeEvent
      - ScaleChangeEvent
      - ScaleDeleteEvent
      - MigrateCreateEvent
      - MigrateAttributeValueChangeEvent
      - MigrateChangeEvent
      - MigrateDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF664_v4.0.0.swagger.json
    subscribedEvents:
    - id: TMF634
      apitype: openapi
      name: ResourceCatalogManagement
      resources:
      - ResourceSpecificationCreateEvent
      - ResourceSpecificationChangeEvent
      - ResourceSpecificationDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF634_v5.0.0.swagger.json
  componentMetadata:
    id: TMFC062
    name: ResourceConfigurationandActivation
    version: 1.1.0
    description: The Resource Configuration and Activation component configures and activates resource instances and enables querying of resource instances to acquire the resource activation states and attributes.
    publicationDate: '2026-06-02'
    status: preview
    functionalBlock: Production
    owners:
    - name: Gaetano Biancardi
      email: redacted
      url: Redacted
    eTOMs:
    - 1.5.8.2.1|Verify_Resource_Configuration|v25.0
    SIDs:
    - Resource_Domain|Resource_Configuration_ABE|v25.0
