apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF620
      required: true
      resources:
      - productSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF622
      required: true
      resources:
      - productOrder:
        - GET /id
        - PATCH
      version: 4
      apiSDO: tmForum
    - id: TMF637
      required: true
      resources:
      - product:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      version: 4
      apiSDO: tmForum
    - id: TMF633
      required: false
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF638
      required: false
      resources:
      - service:
        - GET / id
        - GET
      version: 4
      apiSDO: tmForum
    - id: TMF641
      required: true
      resources:
      - serviceOrder:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelServiceOrder:
        - GET
        - GET /id
        - POST
      version: 4
      apiSDO: tmForum
    - id: TMF634
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF639
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF652
      required: false
      resources:
      - resourceOrder:
        - GET /id
        - POST
      version: 4
      apiSDO: tmForum
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      version: 4
      apiSDO: tmForum
    exposedAPIs:
    - id: TMF622
      required: true
      resources:
      - productOrder:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      - cancelProductOrder:
        - POST
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/hub
      implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChange
      - productOrderCreateEvent
      - productOrderAttributeValueChange
      - productOrderDelete
      - productOrderInformationRequired
      - cancelProductOrderCreateEvent
      - cancelProductOrderStateChange
      - cancelProductOrderInformationRequired
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
   
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents:

    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrderingManagement/call-back
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceOrderingManagement/v4/docs
      implementation: /{{.Release.Name}}-serviceOrderingManagementEvent
      name: ServiceOrder
      port: 80
      resources:
      - serviceOrderStateChangeEvent
      - serviceOrderAttributeValueChangeEvent
      - serviceOrderInformationRequiredEvent
      - serviceOrderMilestoneEvent
      - serviceOrderJeopardyEvent
      - cancelServiceOrderStateChangeEvent
      - cancelServiceOrderInformationRequiredEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF641_ServiceOrdering/master/TMF641-ServiceOrdering-v4.1.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrder/call-back
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceOrder/v4/docs
      implementation: /{{.Release.Name}}-ResourceOrder
      name: ResourceOrder
      port: 80
      resources:
      - resourceOrderStateChange
      - resourceOrderAttributeValueChangeEvent
      - resourceOrderInformationRequiredEvent
      - cancelResourceOrderStateChange
      - cancelResourceOrderInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF652_ResourceOrderManagement/blob/master/TMF652-ResourceOrder-v4.0.0.swagger.json
      apiType: openapi
  componentMetadata:
    id: TMFC003
    name: ProductOrderDeliveryOrchestrationAndManagement
    version: 1.1.1
    description: 'This component orchestrates the delivery of Product Orders (status accepted). 
      Based on the level of Product specification information available in the Product Catalog 
      (eg prerequisite links between product specifications, links between product and CFS specifications...) 
      it determines in which order the product specification level order items need to be delivered, 
      and to which CFS (or Resource) specification each ordered product corresponds, 
      and prepares and addresses each related service (or Resource) order to the production system in charge. 
      During the delivery process execution, this component is in charge of the evolution of the status of 
      the product specification level order items, and of the related product items, triggering updates of the related inventories.'
    publicationDate: 2023-08-18 00:00:00
    status: specified
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.3.3|Customer_Order_Handling|v23.0
    - 1.3.3.8|Manage_Order_Fallout|v23.0
    - 1.3.3.9|Customer_Order_Orchestration|v23.0
    - 1.2.9|Product_Offering_Purchasing|v23.0
    - 1.2.9.5|Complete_Product_Offering_Purchase|v23.0
    - 1.4.5|Service_Configuration_&_Activation|v23.0
    - 1.4.5.6|Issue_Service_Order|v23.0
    - 1.5.6|Resource_Provisioning|v23.0
    - 1.5.6.7|Issue_Resource_Order|v23.0
    functionalFrameworkFunctions:
    - 16|Fallout_Automated_Correction|v23.0
    - 17|Fallout_Correction_Information_Collection|v23.0
    - 18|Fallout_Management_to_Fulfillment_Application_Accessing|v23.0
    - 19|Fallout_Manual_Correction_Queuing|v23.0
    - 20|Fallout_Notification|v23.0
    - 21|Fallout_Orchestration|v23.0
    - 22|Fallout_Reporting|v23.0
    - 23|Fallout_Dashboard_System_Log-in_Accessing|v23.0
    - 24|Pre-populated_Fallout_Information_Presentation|v23.0
    - 175|Customer_Support_Jeopardy_Notification|v23.0
    - 174|Customer_Order_Error_Resolution_Support|v23.0
    - 723|Customer_Order_Item_Decomposition|v23.0
    - 214|Customer_Order_Orchestration|v23.0
    - 215|Retro-active_order_orchestration|v23.0
    - 342|Mass_Service/product_pre-activation|v23.0
    - 743|Number_Portability_Orchestration|v23.0
    - 756|Fallout_Rule_Based_Error_Correction|v23.0
