apiVersion: oda.tmforum.org/v1
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF633
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      - serviceCategory:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF638
      required: false
      resources:
      - service:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF634
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF639
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF669
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF675
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    exposedAPIs:
    - id: TMF645
      required: true
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
      apiSDO: tmForum
    publishedEvents:
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/v4/docs
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/hub
      implementation: /{{.Release.Name}}-ServiceQualification
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationCreateEvent
      - checkServiceQualificationStateChangeEvent
      - checkServiceQualificationInformationRequiredEvent
      - checkServiceQualificationAttributeValueChangeEvent
      - checkServiceQualificationDeleteEvent
      - queryServiceQualificationStateChangeEvent
      - queryServiceQualificationCreateEvent
      - queryServiceQualificationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF645_ServiceQualification/master/TMF645-ServiceQualification-v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents: []
  componentMetadata:
    id: TMFC009
    name: ServiceQualificationManagement
    version: 1.1.0
    description: Service Qualification component is responsible for checking and validating
      the availability of a service according to specified and configured business
      rules. It must identify at least one technical solution (RFSspec) available
      to deliver the service (CFSspec) and check the availability of all the resources
      types involved in this technical solution. No resources are allocated during
      Service Qualification. Service Qualification component has functionality that
      include checking service feasibility status and publishing or reporting service
      qualification result, but also calculated service delivery due date and identified
      need of an appointment at the customer site. Service Qualification can also
      be in charge of the cost calculation of the technical solution identified, when
      it cannot be determined at catalog design time (complex B2B services). This
      information will be used as an input to price calculation.
    publicationDate: 2023-08-18 00:00:00
    status: specified
    functionalBlock: Production
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.4.5-Service_Configuration_&_Activation-v23.0
    functionalFrameworkFunctions:
    - 319-Service_Feasibility_Checking-v23.0
    - 586-Service_Availability_Validation-v23.0
    - 571-Service_Delivery_Due_Date_Calculation-v23.0
