apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalogManagement/v4/docs
      id: TMF633
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalogManagement/v4
      port: 8080
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      - serviceCategory:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/v4/docs
      id: TMF638
      implementation: /{{.Release.Name}}-ServiceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/v4
      port: 8080
      required: false
      resources:
      - service:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceCatalog
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4
      port: 8080
      required: false
      resources:
      - resourceSpecification:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF639
      implementation: /{{.Release.Name}}-ResourceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4
      port: 8080
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
      id: TMF632
      implementation: /{{.Release.Name}}-PartyManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4
      port: 8080
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4/docs
      id: TMF669
      implementation: /{{.Release.Name}}-PartyRoleManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4
      port: 8080
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4/docs
      id: TMF673
      implementation: /{{.Release.Name}}-GeographicAddressManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
      port: 8080
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
      id: TMF674
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
      port: 8080
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4/docs
      id: TMF675
      implementation: /{{.Release.Name}}-GeographicLocation
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4
      port: 8080
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4/docs
      id: TMF672
      implementation: /{{.Release.Name}}-UserRolesPermissions
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4
      port: 8080
      required: false
      resources:
      - permission:
        - GET
        - GET /id
      version: 4
    - id: TMF688
      required: false
      resources:
      - event:
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - developerUI: /{{.Release.Name}}-{{.Values.oda.component.type}}/tmf-api/ServiceQualificationManagement/v4/docs
      id: TMF645
      implementation: /{{.Release.Name}}-ServiceQualificationManagement
      path: /{{.Release.Name}}-{{.Values.oda.component.type}}/tmf-api/ServiceQualificationManagement/v4/
      port: 8080
      required: true
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
    publishedEvents:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.oda.component.type}}/tmf-api/ServiceQualification/v4/docs
      hub: /{{.Release.Name}}-{{.Values.oda.component.type}}/tmf-api/ServiceQualification/hub
      implementation: /{{.Release.Name}}-ServiceQualification
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationCreateEvent
      - checkServiceQualificationStateChangeEvent
      - checkServiceQualificationInformationRequiredEvent
      - checkServiceQualificationAttributeValueChangeEvent
      - checkServiceQualificationDeleteEvent
      - queryServiceQualificationStateChangeEvent
      - queryServiceQualificationCreateEvent
      - queryServiceQualificationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF645_ServiceQualification/master/TMF645-ServiceQualification-v4.0.0.swagger.json
    subscribedEvents: []
  description: Service Qualification component is responsible for checking and validating
    the availability of a service according to specified and configured business rules.
    It must identify at least one technical solution (RFSspec) available to deliver
    the service (CFSspec) and check the availability of all the resources types involved
    in this technical solution. No resources are allocated during Service Qualification.
    Service Qualification component has functionality that include checking service
    feasibility status and publishing or reporting service qualification result, but
    also calculated service delivery due date and identified need of an appointment
    at the customer site. Service Qualification can also be in charge of the cost
    calculation of the technical solution identified, when it cannot be determined
    at catalog design time (complex B2B services). This information will be used as
    an input to price calculation.
  functionalBlock: Production
  id: TMFC009
  maintainers:
  - email: Anastasios.sarantis@cityfibre.com
    name: Tassos Sarantis
  name: ServiceQualificationManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: Anastasios.sarantis@cityfibre.com
    name: Tassos Sarantis
  publicationDate: 2023-08-18 00:00:00
  status: specified
  version: 1.1.1
