apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: 4
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF669
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: 4
        resources:
        - partyRole:
          - GET
          - GET /id
    - id: TMF662
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - entitySpecification:
          - GET
          - GET /id
        - entityCategory:
          - GET
          - GET /id
        - entityCatalog:
          - GET
          - GET /id
        - entityCatalogItem:
          - GET
          - GET /id
    - id: TMF667
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - document:
          - GET
          - GET /id
    - id: TMF681
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - communicationMessage:
          - GET
          - GET /id
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - PATCH
    exposedAPIs:
    - id: TMF683
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - partyInteraction:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
      - version: 4
        resources:
        - partyInteraction:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    publishedEvents:
    - id: TMF683
      name: PartyInteractionManagement
      resources:
      - partyInteractionCreateEvent
      - partyInteractionAttributeValueChangeEvent
      - partyInteractionDeleteEvent
      - partyInteractionStatusChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF683_v5.0.0.swagger.json
      apiType: openapi
    - id: TMF701
      name: ProcessFlowManagement
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF701_Process_Management/5.0.0/swagger/TMF701-ProcessManagement-v5.0.0.oas.yaml
      apiType: openapi
    subscribedEvents:
    - id: TMF632
      name: PartyManagement
      resources:
      - individualCreateEvent
      - individualAttributeValueChangeEvent
      - individualStateChangeEvent
      - individualDeleteEvent
      - organizationCreateEvent
      - organizationAttributeValueChangeEvent
      - organizationStateChangeEvent
      - organizationDeleteEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v5.0.0.swagger.json
      apiType: openapi
    - id: TMF669
      name: PartyRoleManagement
      resources:
      - partyRoleCreateEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF669_v5.0.0.swagger.json
      apiType: openapi
    - id: TMF667
      name: documentManagement
      resources:
      - documentChangeEvent
      - documentSpecificationAttributeValueChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF667_v4.0.0.swagger.json
      apiType: openapi
    - id: TMF701
      name: ProcessFlowManagement
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF701_Process_Management/5.0.0/swagger/TMF701-ProcessManagement-v5.0.0.oas.yaml
      apiType: openapi
  componentMetadata:
    id: TMFC023
    name: PartyInteractionManagement
    version: 1.2.2
    description: Party Interaction deals with the initial greeting and welcoming of a new contact. This will typically be the first component in a customer experience journey, shared by unassisted (self-service, retail kiosk) or assisted (call center, retail store) channels. It will identify known Parties or new Parties and react appropriately to propose available actions. It records all the interactions for the Parties from all channels.
    publicationDate: 2025-10-21
    status: production
    functionalBlock: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.3.5|Customer_Interaction_Management|v24.0
    - 1.3.5.1|Create_Customer_Interaction|v24.0
    - 1.3.5.2|Update_Customer_Interaction|v24.0
    - 1.3.5.3|Close_Customer_Interaction|v24.0
    - 1.3.5.4|Log_Customer_Interaction|v24.0
    - 1.3.5.6|Track_and_Manage_Customer_Interaction|v24.0
    - 1.3.5.7|Report_Customer_interaction|v24.0
    - 1.6.9|Business_Partner_Interaction_Management|v24.0
    - 1.6.9.1|Log_Business_Partner_Interaction|v24.0
    - 1.6.9.3|Track_and_Manage_Business_Partner_Interaction|v24.0
    - 1.6.9.5|Analyze_&_Report_Business_Partner_Interactions|v24.0
    functionalFrameworkFunctions:
    - 93|Customer_Behavior_Tracking|v24.0
    - 163|Contact_Queuing|v24.0
    - 165|Customer_Support_Collaboration_Access|v24.0
    - 168|Voice_Channel_Contact_Routing|v24.0
    - 189|Customer_Interaction_Information_Capturing|v24.0
    - 191|Customer_Relationship/Context_Event_Data_Accumulation|v24.0
    - 196|Customer_Interaction_Logging|v24.0
    - 239|Recommendation_to_Customer_Notification|v24.0
    - 1041|Partner_Interaction_Journalizing|v24.0
    SIDs:
    - Shared_Domain|Communication_Interaction_ABE|v25.0
