apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: ProductConfigurator
  id: TMFC027
  functionalBlock: CoreCommerceManagement
  description: The Product Configurator ODA Component is empowering sales by offering
    the right product combinations, controlling discounting, and automating approvals
    through support of configuration, pricing and quote generation activities.
  publicationDate: 2023-11-27
  status: specified
  version: 2.1.1
  coreFunction:
    dependentAPIs:
    - id: TMF637
      required: true
      resources:
      - product:
        - GET
        - GET /id
      version: 4
    - id: TMF620
      required: true
      resources:
      - catalog:
        - GET
        - GET /id
      - category:
        - GET
        - GET /id
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF622
      required: true
      resources:
      - productOrder:
        - GET
        - GET /id
      version: 4
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
    - id: TMF666
      required: false
      resources:
      - billingAccount:
        - GET
        - GET /id
      version: 4
    - id: TMF669
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      version: 4
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    - id: TMF662
      required: false
      resources:
      - entityCatalog:
        - GET
        - GET /id
      version: 4
    - id: TMF921
      required: false
      resources:
      - intent:
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - id: TMF679
      required: true
      resources:
      - productOfferingQualification:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE
      version: 4
    - id: TMF760
      required: true
      resources:
      - checkProductConfiguration:
        - GET
        - GET/id
        - POST
      - queryProductConfiguration:
        - GET
        - GET/id
        - POST
      version: 5
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - GET
        - get /id
        - PATCH
      version: 4
    publishedEvents:
    - implementation: /{{.Release.Name}}-ProductConfiguration
      name: ProductConfiguration
      port: 80
      resources:
      - checkProductConfigurationAttributeValueChangeEvent
      - checkProductConfigurationCreateEvent
      - checkProductConfigurationDeleteEvent
      - checkProductConfigurationStateChangeEvent
      specification: ''
      apiType: openapi
    - implementation: /{{.Release.Name}}-ProductOfferingQualification
      name: ProductOfferingQualification
      port: 80
      resources:
      - queryProductConfigurationAttributeValueChangeEvent
      - queryProductConfigurationCreateEvent
      - queryProductConfigurationDeleteEvent
      - queryProductConfigurationStateChangeEvent
      specification: ''
      apiType: openapi
    - implementation: /{{.Release.Name}}-pdtquali
      name: ProductConfiguration
      port: 80
      resources:
      - ProductOfferingQualificationCreateEvent
      - ProductOfferingQualificationAttributeValueChangeEvent
      - ProductOfferingQualificationStateChangeEvent
      - ProductOfferingQualificationDeleteEvent
      - ProductOfferingQualificationInformationRequiredEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF679_ProductOfferingQualificationManagement/master/TMF679-ProductOfferingQualificationManagement-v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - name: ProductCatalogManagement
      port: 80
      resources:
      - CatalogCreateEvent
      - CatalogAttributeValueChangeEvent
      - CatalogStateChangeEvent
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF622-ProductCatalogManagement/blob/master/TMF622-ProductCatalogManagement-v4.0.0.swagger.json
      apiType: openapi
  owners:
  - email: Redacted
    name: Redacted
  maintainers:
  - name: Redacted
    email: components@tmforum.org
