apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF637
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - product:
          - GET
          - GET /id
      - version: 4
        resources:
        - product:
          - GET
          - GET /id
    - id: TMF620
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - productCatalog:
          - GET
          - GET /id
        - category:
          - GET
          - GET /id
        - productOffering:
          - GET
          - GET /id
        - productOfferingPrice:
          - GET
          - GET /id
        - productSpecification:
          - GET
          - GET /id
      - version: 4
        resources:
        - catalog:
          - GET
          - GET /id
        - category:
          - GET
          - GET /id
        - productOffering:
          - GET
          - GET /id
        - productOfferingPrice:
          - GET
          - GET /id
        - productSpecification:
          - GET
          - GET /id
    - id: TMF622
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - productOrder:
          - GET
          - GET /id
      - version: 4
        resources:
        - productOrder:
          - GET
          - GET /id
    - id: TMF632
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: 4
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF666
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - billingAccount:
          - GET
          - GET /id
      - version: 4
        resources:
        - billingAccount:
          - GET
          - GET /id
    - id: TMF669
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: 4
        resources:
        - partyRole:
          - GET
          - GET /id
    - id: TMF673
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - geographicAddress:
          - GET
          - GET /id
        - geographicSubAddress:
          - GET
          - GET /id
    - id: TMF674
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - geographicSite:
          - GET
          - GET /id
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    - id: TMF662
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - entityCatalog:
          - GET
          - GET /id
    - id: TMF921
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - intent:
          - GET
          - GET /id
      - version: 4
        resources:
        - intent:
          - GET
          - GET /id
    - id: TMF645
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - checkServiceQualification:
          - GET
          - GET /id
          - POST
          - PATCH
        - queryServiceQualification:
          - GET
          - GET /id
          - POST
          - PATCH
      - version: 4
        resources:
        - checkServiceQualification:
          - GET
          - GET /id
          - POST
          - PATCH
        - queryServiceQualification:
          - GET
          - GET /id
          - POST
          - PATCH
    - id: TMF651
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - agreement:
          - GET
          - GET /id
    exposedAPIs:
    - id: TMF679
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - productOfferingQualification:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE
    - id: TMF760
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - checkProductConfiguration:
          - GET
          - POST
        - queryProductConfiguration:
          - GET
          - POST
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - GET
          - get /id
          - PATCH
    publishedEvents:
    - implementation: /{{.Release.Name}}-ProductConfiguration
      name: ProductConfiguration
      port: 80
      resources:
      - checkProductConfigurationAttributeValueChangeEvent
      - checkProductConfigurationCreateEvent
      - checkProductConfigurationDeleteEvent
      - checkProductConfigurationStateChangeEvent
      - queryProductConfigurationAttributeValueChangeEvent
      - queryProductConfigurationCreateEvent
      - queryProductConfigurationDeleteEvent
      - queryProductConfigurationStateChangeEvent
      specification: ''
      apiType: openapi
    - implementation: /{{.Release.Name}}-pdtquali
      name: ProductConfiguration
      port: 80
      resources:
      - ProductOfferingQualificationCreateEvent
      - ProductOfferingQualificationAttributeValueChangeEvent
      - ProductOfferingQualificationStateChangeEvent
      - ProductOfferingQualificationDeleteEvent
      - ProductOfferingQualificationInformationRequiredEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF679_ProductOfferingQualificationManagement/master/TMF679-ProductOfferingQualificationManagement-v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - name: ProductCatalogManagement
      port: 80
      resources:
      - CatalogCreateEvent
      - CatalogAttributeValueChangeEvent
      - CatalogStateChangeEvent
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF622-ProductCatalogManagement/blob/master/TMF622-ProductCatalogManagement-v4.0.0.swagger.json
      apiType: openapi
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/call-back
      implementation: /{{.Release.Name}}-ServiceQualificationEvent
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF645_ServiceQualification/blob/master/TMF645-ServiceQualification-v4.0.0.swagger.json
  componentMetadata:
    id: TMFC027
    name: ProductConfigurator
    version: 2.2.1
    description: The Product Configurator component empowers sales by offering the right product combinations, controlling discounting, and automating approvals through support of configuration, pricing and quote generation activities.
    publicationDate: 2026-06-02
    status: preview
    functionalBlock: CoreCommerce
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.2.5|Product_Domain|Product_Configuration_Management|v25.0
    - 1.2.5|Product_Domain|Manage_Product_Configuration|v25.0
    functionalFrameworkFunctions:
    - 55|Price_&_Discount_Calculation|v25.0
    - 182|Inter_Product_Dependency_Identification|v25.0
    - 205|Customer_Order_Eligibility_Validation|v25.0
    - 207|Offer_and_Product_Configuration|v25.0
    - 262|Product_Availability_Checking_1_|v25.0
    - 274|Quote_Price_Support_Access|v25.0
    - 278|Customer_SLA_Preferences_Capturing|v25.0
    - 300|Discount_Calculation|v25.0
    - 320|Customer_Product_Proposal_Creation|v25.0
    - 379|Product_Customization_Offering_Management|v25.0
    - 727|Product_Offer_to_Customer_Verification_2|v25.0
    - 928|Solution_Design_Creation|v25.0
    - 930|Automatic_Solution_Validation|v25.0
    - 931|Solution_Pricing|v25.0
    - 932|Calculation_Rules_Retrieval|v25.0
    - 933|Price/Cost_Optimization_|v25.0
    SIDs:
    - Product_Domain|Product_Configuration_ABE|ProductConfiguration_BE|v25.0
