apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: WorkforceManagement
  id: TMFC046
  functionalBlock: Production
  description: Workforce Management provides capabilities to describe teams, organizations,
    skills and availability of sales / technical experts. It provides the ability
    in reserving time slots to carry out assigned task (internal or customer facing).
    It allows the reservation (and their updates / reschedule) of appointments and
    interventions. option, etc.)
  publicationDate: 2024-04-18 00:00:00
  status: specified
  version: 1.0.0
  coreFunction:
    dependentAPIs:
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF669
      required: false
      resources:
      - PartyRole:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF672
      required: true
      resources:
      - permission:
        - GET
        - GET /id
      - userRole:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF688
      required: false
      resources:
      - event:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    exposedAPIs:
    - id: TMF646
      required: true
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      version: 4
      name: _must_be_defined
      apiType: openapi
      implementation: _must_be_defined
      path: _must_be_defined
      port: _must_be_defined
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      version: 4
      name: _must_be_defined
      apiType: openapi
      implementation: _must_be_defined
      path: _must_be_defined
      port: _must_be_defined
    - id: TMF688
      required: false
      resources:
      - listener:
        - POST
      - hub:
        - POST
        - DELETE /id
      version: 4
      name: _must_be_defined
      apiType: openapi
      implementation: _must_be_defined
      path: _must_be_defined
      port: _must_be_defined
  owners:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  eventNotification:
    publishedEvents:
    - implementation: /{{.Release.Name}}-appointmentManagement
      name: appointmentManagement
      port: 80
      resources:
      - appointmentStateChange
      - appointmentCreateEvent
      - appointmentAttributeValueChangeEvent
      - appointmentDeleteEvent
      - searchTimeSlotCreateEvent
      - searchTimeSlotAttributeValueChangeEvent
      - searchTimeSlotStateChangeEvent
      - searchTimeSlotDeleteEvent
      specification: https://github.com/tmforum-apis/TMF646_AppointmentManagement/blob/master/TMF646-Appointment-v4.0.0.swagger.json
      id: TMF646
      apiType: openapi
    subscribedEvents:
    - name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      id: TMF669
      apiType: openapi
    - name: UserRolePermissionManagement
      port: 80
      resources:
      - permissionCreateEvent
      - permissionAttributeValueChangeEvent
      - permissionStateChangeEvent
      - permissionDeleteEvent
      - userRoleCreateEvent
      - userRoleAttributeValueChangeEvent
      - userRoleStateChangeEvent
      - userRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF672_UserRolesPermissions/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
      id: TMF672
      apiType: openapi
    - name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      id: TMF701
      apiType: openapi
