apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF633
      required: true
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - serviceSpecification:
          - GET
          - GET /id
    - id: TMF669
      required: false
      specification:
      - version: 5
        apiSDO: tmForum
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: 4
        apiSDO: tmForum
        resources:
        - PartyRole:
          - GET
          - GET /id
    - id: TMF639
      required: false
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - resource:
          - GET
          - GET /id
    - id: TMF638
      required: false
      specification:
      - version: 5
        apiSDO: tmForum
        resources:
        - service:
          - GET
          - GET /id
      - version: 4
        apiSDO: tmForum
        resources:
        - service:
          - GET
          - GET /id
    - id: TMF673
      required: false
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - geographicAddress:
          - GET
          - GET /id
        - geographicSubAddress:
          - GET
          - GET /id
    - id: TMF674
      required: false
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - geographicSite:
          - GET
          - GET /id
    - id: TMF675
      required: false
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - geographicLocation:
          - GET
          - GET /id
    - id: TMF641
      required: false
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - serviceOrder:
          - GET
          - GET /id
    - id: TMF632
      required: false
      specification:
      - version: 5
        apiSDO: tmForum
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: 4
        apiSDO: tmForum
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    exposedAPIs:
    - id: TMF638
      required: true
      specification:
      - version: 5
        apiSDO: tmForum
        resources:
        - service:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
      - version: 4
        apiSDO: tmForum
        resources:
        - service:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF701
      required: false
      specification:
      - version: 4
        apiSDO: tmForum
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceInventory/hub
      implementation: /{{.Release.Name}}-serviceInventoryEvent
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceAttributeValueChangeEvent
      - serviceStateChangeEvent
      - serviceDeleteEvent
      specification: https://github.com/tmforum-apis/TMF638_ServiceInventoryManagement/blob/master/TMF638_ServiceInventoryManagement-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Resource/call-back
      implementation: /{{.Release.Name}}-ResourceInventoryManagement
      name: ResourceInventoryManagement
      port: 80
      resources:
      - resourceDeleteEvent
      specification: https://open-api.tmforum.org20-ResourceInventory-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/call-back
      implementation: /{{.Release.Name}}-ServiceInventoryManagement
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceAttributeValueChangeEvent
      - serviceStateChangeEvent
      - serviceDeleteEvent
      specification: https://open-api.tmforum.org20-ServiceInventory-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/call-back
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationDeleteEvent
      specification: https://open-api.tmforum.org20-ServiceCatalog-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/call-back
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://open-api.tmforum.org20-PartyRole-v4.0.0.swagger.json
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSite/call-back
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      name: GeographicSiteManagement
      port: 80
      resources:
      - geographicSiteDeleteEvent
      specification: https://open-api.tmforum.org20-GeographicSite-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/call-back
      implementation: /{{.Release.Name}}-GeographicLocation
      name: GeographicLocation
      port: 80
      resources:
      - geographicLocationDeleteEvent
      specification: https://open-api.tmforum.org20-GeographicLocatin-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/call-back
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://open-api.tmforum.org20-Party-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceOrdering/call-back
      implementation: /{{.Release.Name}}-ServiceOrderingManagement
      name: ServiceOrderingManagement
      port: 80
      resources:
      - serviceOrderDeleteEvent
      specification: https://open-api.tmforum.org20-ServiceOrdering-v4.0.0.swagger.json
      apiType: openapi
  componentMetadata:
    id: TMFC008
    name: ServiceInventory
    version: 1.3.0
    description: The Service Inventory component is responsible for storage and exposure of CFS (Customer Facing Services) that are associated to Product Inventory items. It is also responsible for RFS (Resource Facing Service) definition, mapping between CFS and RFS and mapping with infrastructure/network resources. The Service Inventory component has functionality that enables creation of inventory items, inventory organization, inventory search or filter, inventory monitoring and tracking, inventory control and inventory auditing. The minimum check to be performed at inventory item creation or update is for global consistency with the related Service Catalog information.
    publicationDate: 2024-11-12 00:00:00
    status: Preview
    functionalBlock: Production
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.4.4|Service_Support_Readiness|v23.0
    - 1.4.4.1|Manage_Service_Inventory|v23.0
    functionalFrameworkFunctions:
    - 576|Service_Data_Retrieval|v23.0
    - 593|Service_Inventory_Repository_Updating|v23.0
    - 628|Service_to_Resource_Relationship_Management|v23.0
    - 629|Service_to_Resource_Relationship_Synchronization|v23.0
    - 630|Service-Resource_Relationship_Management_Notifications|v23.0
    - 964|Onboarded_Service_Integration_Configuration|v23.0
    - 965|Service_Instance_Lifecycle_Management|v23.0
    - 1344|Service_Topology_Discovery|v23.0
    SIDs:
    - Service_Domain|Service_ABE|v25.0
  apiSDO: tmForum
