apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: ServiceInventory
  id: TMFC008
  functionalBlock: Production
  description: Service Inventory component is responsible for storage and exposure
    of CFS (Customer Facing Service) that are associated to Product Inventory items.
    It is also responsible for RFS (Resource Facing Service) definition, mapping between
    CFS and RFS and mapping with infrastructure/network resources. Service Inventory
    component has functionality that enables inventory items creation, inventory organization,
    inventory search or filter, inventory monitoring and tracking, inventory control
    and inventory auditing.The minimum check to be performed at inventory items creation
    or update is the global consistency with related Service Catalog information.
  publicationDate: 2024-11-12 00:00:00
  status: specified
  version: 1.2.0
  coreFunction:
    dependentAPIs:
    - id: TMF633
      required: true
      resources:
      - serviceSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF669
      required: false
      resources:
      - PartyRole:
        - GET
        - GET /id
      version: 4
    - id: TMF639
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      version: 4
    - id: TMF638
      required: false
      resources:
      - service:
        - GET
        - GET /id
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      version: 4
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
    - id: TMF675
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      version: 4
    - id: TMF641
      required: false
      resources:
      - serviceOrder:
        - GET
        - GET /id
      version: 4
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - id: TMF638
      required: true
      resources:
      - service:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/serviceInventory/hub
      implementation: /{{.Release.Name}}-serviceInventoryEvent
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceAttributeValueChangeEvent
      - serviceStateChangeEvent
      - serviceDeleteEvent
      specification: https://github.com/tmforum-apis/TMF638_ServiceInventoryManagement/blob/master/TMF638_ServiceInventoryManagement-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Resource/call-back
      implementation: /{{.Release.Name}}-ResourceInventoryManagement
      name: ResourceInventoryManagement
      port: 80
      resources:
      - resourceDeleteEvent
      specification: https://open-api.tmforum.org20-ResourceInventory-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/call-back
      implementation: /{{.Release.Name}}-ServiceInventoryManagement
      name: ServiceInventoryManagement
      port: 80
      resources:
      - serviceCreateEvent
      - serviceAttributeValueChangeEvent
      - serviceStateChangeEvent
      - serviceDeleteEvent
      specification: https://open-api.tmforum.org20-ServiceInventory-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/call-back
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - serviceSpecificationDeleteEvent
      specification: https://open-api.tmforum.org20-ServiceCatalog-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/call-back
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://open-api.tmforum.org20-PartyRole-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      name: GeographicSiteManagement
      port: 80
      resources:
      - geographicSiteDeleteEvent
      specification: https://open-api.tmforum.org20-GeographicSite-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/call-back
      implementation: /{{.Release.Name}}-GeographicLocation
      name: GeographicLocation
      port: 80
      resources:
      - geographicLocationDeleteEvent
      specification: https://open-api.tmforum.org20-GeographicLocatin-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/call-back
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - individualDeleteEvent
      - organizationDeleteEvent
      specification: https://open-api.tmforum.org20-Party-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceOrdering/call-back
      implementation: /{{.Release.Name}}-ServiceOrderingManagement
      name: ServiceOrderingManagement
      port: 80
      resources:
      - serviceOrderDeleteEvent
      specification: https://open-api.tmforum.org20-ServiceOrdering-v4.0.0.swagger.json
      apiType: openapi
  owners:
  - email: Redacted
    name: Redacted
  maintainers:
  - name: Redacted
    email: components@tmforum.org
  eTOMs:
  - 1.4.4_Service_Support_Readiness_v23.0
  - 1.4.4.1_Manage_Service_Inventory_v23.0
  functionalFrameworkFunctions:
  - 576_Service_Data_Retrieval_v23.0
  - 593_Service_Inventory_Repository_Updating_v23.0
  - 628_Service_to_Resource_Relationship_Management_v23.0
  - 629_Service_to_Resource_Relationship_Synchronization_v23.0
  - 630_Service-Resource_Relationship_Management_Notifications_v23.0
  - 964_Onboarded_Service_Integration_Configuration_v23.0
  - 965_Service_Instance_Lifecycle_Management_v23.0
  - 1344_Service_Topology_Discovery_v23.0  
