apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      required: true
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4.0
    - id: TMF669
      required: true
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4.0
    - id: TMF672
      required: true
      resources:
      - permission:
        - GET
        - GET /id
      - userRole:
        - GET
        - GET /id
      version: 4.0
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      version: 4.0
    - id: TMF688
      required: false
      resources:
      - event:
        - GET
        - GET /id
      version: 4.0
    - id: TMF667
      required: false
      resources:
      - document:
        - GET
        - GET /id
        - POST
      version: 4.0
    - id: TMF620
      required: false
      resources:
      - productOffering:
        - GET
        - GET /id
      version: 4.1
    exposedAPIs:
    - id: TMF644
      required: true
      resources:
      - PartyPrivacyProfileSpecification:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE
      - PartyPrivacyProfile:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE
      - PartyPrivacyAgreement:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE
      version: 4.0
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      version: 4.0
    - id: TMF688
      required: false
      resources:
      - listener:
        - POST
      - hub:
        - POST
        - DELETE /id
      version: 4.0
    publishedEvents:
    - apitype: openapi
      implementation: /{{.Release.Name}}-PrivacyManagement
      name: PrivacyManagement
      port: 8080
      resources:
      - PartyPrivacyProfileCreateEvent
      - PartyPrivacyProfileAttributeValueChangeEvent
      - PartyPrivacyProfileDeleteEvent
      - PartyPrivacyProfileStatusChangeEvent
      - PartyPrivacyProfileSpecificationCreateEvent
      - PartyPrivacyProfileSpecificationAttributeValueChangeEvent
      - PartyPrivacyProfileSpecificationDeleteEvent
      - PartyPrivacyProfileSpecificationStatusChangeEvent
      - PartyPrivacyAgreementCreateEvent
      - PartyPrivacyAgreementAttributeValueChangeEvent
      - PartyPrivacyAgreementDeleteEvent
      - PartyPrivacyAgreementStatusChangeEvent
      specification: https://github.com/tmforum-apis/TMF644_Privacy/blob/master/TMF644-Privacy-v4.0.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    - apitype: openapi
      name: UserRolePermissionManagement
      port: 80
      resources:
      - permissionDeleteEvent
      specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRoleandPermission-v4.0.0.swagger.json
    - name: PartyManagement
      port: 80
      resources:
      - IndividualDeleteEvent
      - OrganizationDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    - name: ProductCatalogManagement
      port: 80
      resources:
      - ProductOfferingDeleteEvent
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
  description: 'The Party Privacy Management component aims to: define the Privacy
    Policy rules established by the CSP, according to applicable regulations, such
    as GDPR in Europe, apply these rules to each Party interacting with the CSP and
    to all of their personnal information and personally identifiable information
    (PII); register explicit opt-in and opt-out given by Parties regarding the usage
    of some of their personal information for dedicated purpose, such as marketing.'
  functionalBlock: PartyManagement
  id: TMFC022
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  name: PartyPrivacyManagement
  owners:
  - email: sylvie.demarest@orange.com
    name: sylvie Demarest
  publicationDate: 2023-11-28
  status: specified
  version: 1.0.0
