apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentId: TMFC022
  componentName: PartyPrivacyManagement
  componentFunctionalBlock: PartyManagement 
  componenentDescription: "The Party Privacy Management component aims to: define the Privacy Policy rules established by the CSP, according to applicable regulations, such as GDPR in Europe, apply these rules to each Party interacting with the CSP and to all of their personnal information and personally identifiable information (PII); register explicit opt-in and opt-out given by Parties regarding the usage of some of their personal information for dedicated purpose, such as marketing."
  componentVersion: 1.0.0
  componentStatus: specified 
  componentPublicationDate: 2023-11-28
  maintainers:
    - name: Gaetano Biancardi
      email: gaetano.biancardi@accenture.com
  owners: 
    - name: sylvie Demarest
      email: sylvie.demarest@orange.com
coreFunction:
  exposedAPIs:
    - name: PrivacyManagement
      id: TMF644
      isRequired: yes
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF644_Privacy/blob/master/TMF644-Privacy-v4.0.0.swagger.json 
      implementation: '/{{.Release.Name}}-PrivacyManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PrivacyManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PrivacyManagement/v4/docs
      port: 8080
      resources:
        - PartyPrivacyProfileSpecification:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE
        - PartyPrivacyProfile:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE          
        - PartyPrivacyAgreement:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE              
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: no
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-procmngttapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources:
        - processFlow:
            - GET
            - GET /id
            - POST
            - DELETE /id
        - taskFlow:
            - GET
            - GET /id
            - PATCH /id
    - name: Event
      id: TMF688
      isRequired: no
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PromotionManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources:
        - listener:
          - POST
        - hub:
          - POST
          - DELETE /id
  dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: yes
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: yes
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyRole:
            - GET
            - GET /id
    - name: UserRolePermissionManagement
      id: TMF672
      isRequired: yes
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - permission:
            - GET
            - GET /id
        - userRole:
            - GET
            - GET /id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: no
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - processFlow:
            - POST
            - GET
            - GET /id
            - PATCH
    - name: Event
      id: TMF688
      isRequired: no
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - event:
            - GET
            - GET /id
    - name: Document
      id: TMF667
      isRequired: no
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF667_Document/blob/master/TMF667-Document-v4.0.0.swagger.json
      apitype: openapi
      port: 8080
      resources: 
       - document:
                - GET
                - GET /id
                - POST      
    - name: ProductCatalogManagement 
      id: TMF620
      isRequired: no
      version: 4.1
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json     
      apitype: openapi     
      resources: 
      - productOffering:  
        - GET
        - GET /id                        
  publishedEvents:
    - name: PrivacyManagement
      specification: https://github.com/tmforum-apis/TMF644_Privacy/blob/master/TMF644-Privacy-v4.0.0.swagger.json 
      apitype: openapi
      port: 8080
      resources:
        - PartyPrivacyProfileCreateEvent
        - PartyPrivacyProfileAttributeValueChangeEvent
        - PartyPrivacyProfileDeleteEvent
        - PartyPrivacyProfileStatusChangeEvent
        - PartyPrivacyProfileSpecificationCreateEvent
        - PartyPrivacyProfileSpecificationAttributeValueChangeEvent
        - PartyPrivacyProfileSpecificationDeleteEvent
        - PartyPrivacyProfileSpecificationStatusChangeEvent
        - PartyPrivacyAgreementCreateEvent
        - PartyPrivacyAgreementAttributeValueChangeEvent
        - PartyPrivacyAgreementDeleteEvent
        - PartyPrivacyAgreementStatusChangeEvent

  subscribedEvents:
    - name: PartyRoleManagement
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      port: 80
      resources:
        - partyRoleDeleteEvent
    - name: UserRolePermissionManagement
      specification: >-
        https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRoleandPermission-v4.0.0.swagger.json
      apitype: openapi
      port: 80
      resources:
        - permissionDeleteEvent
    - name: PartyManagement  
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      port: 80
      resources:
       - IndividualDeleteEvent
       - OrganizationDeleteEvent
    - name: ProductCatalogManagement  
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json     
      port: 80
      resources:
       - ProductOfferingDeleteEvent   

managementFunction: []
reportingFunction: []
securityFunction: []
