apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - individual:
          - GET
        - organization:
          - GET
      - version: 4
        resources:
        - individual:
          - GET
          - GET/id
        - organization:
          - GET
          - GET/id
    - id: TMF669
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - partyRole:
          - GET
          - GET /id
      - version: 4
        resources:
        - partyRole:
          - GET
          - GET/id
    - id: TMF620
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - productOffering:
          - GET
        - productOfferingPrice:
          - GET
      - version: 4
        resources:
        - productOffering:
          - GET
          - GET/id
        - productOfferingPrice:
          - GET
          - GET/id
    - id: TMF651
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - agreement:
          - GET
          - GET/id
        - agreementSpecification:
          - GET
          - GET/id
    - id: TMF648
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - quote:
          - GET
          - GET /id
    - id: TMF622
      apiSDO: tmForum
      required: false
      specification:
      - version: 5
        resources:
        - productOrder:
          - GET
          - GET /id
      - version: 4
        resources:
        - productOrder:
          - GET
          - GET /id
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    exposedAPIs:
    - id: TMF699
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - salesLead:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
        - salesOpportunity:
          - GET
          - GET /id
          - POST
          - PATCH
          - DELETE
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/hub
      implementation: /{{.Release.Name}}-SalesManagement
      name: SalesManagement
      port: 80
      resources:
      - SalesLeadCreateEvent
      - SalesLeadAttributeValueChangeEvent
      - SalesLeadStateChangeEvent
      - SalesLeadDeleteEvent
      - SalesOpportunityCreateEvent
      - SalesOpportunityAttributeValueChangeEvent
      - SalesOpportunityStateChangeEvent
      - SalesOpportunityDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - processFlowSpecificationAttributeValueChangeEvent
      - processFlowSpecificationCreateEvent
      - processFlowSpecificationDeleteEvent
      - processFlowSpecificationStateChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      - taskFlowSpecificationAttributeValueChangeEvent
      - taskFlowSpecificationCreateEvent
      - taskFlowSpecificationDeleteEvent
      - taskFlowSpecificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
      implementation: /{{.Release.Name}}-ProductCatalogManagement
      name: ProductCatalogManagement
      port: 80
      resources:
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
      implementation: /{{.Release.Name}}-ProductOrder
      name: ProductOrder
      port: 80
      resources:
      - ProductOrderCreateEvent
      - ProductOrderAttributeValueChangeEvent
      - ProductOrderDeleteEvent
      - ProductOrderStateChangeEvent
      - ProductOrderInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/ProductOrder/TMF622-ProductOrder-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Agreement/call-back
      implementation: /{{.Release.Name}}-Agreement
      name: AgreementManagement
      port: 80
      resources:
      - AgreementCreateEvent
      - AgreementAttributeValueChangeEvent
      - AgreementStateChangeEvent
      - AgreementDeleteEvent
      - AgreementSpecificationCreateEvent
      - AgreementSpecificationAttributeValueChangeEvent
      - AgreementSpecificationStateChangeEvent
      - AgreementSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/QuoteManagement/call-back
      implementation: /{{.Release.Name}}-QuoteManagement
      name: QuoteManagement
      port: 80
      resources:
      - QuoteCreateEvent
      - QuoteStateChangeEvent
      - QuoteDeleteEvent
      - QuoteInformationRequiredEvent
      - QuoteAttributeValueChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
      apiType: openapi
    - call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - PartyRoleCreateEvent
      - PartyRoleAttributeValueChangeEvent
      - PartyRoleStateChangeEvent
      - PartyRoleDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
  componentMetadata:
    id: TMFC036
    name: LeadAndOpportunityManagement
    version: 1.3.0
    description: Lead and Opportunity Management component provides the functionality for lead and opportunity capture, qualification, reporting, and support during the pre-sales stage.
    publicationDate: 2026-05-21
    status: preview
    functionalBlock: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs:
    - 1.1.11|Contact/Lead/Prospect_Management|v23.0
    - 1.1.11.1|Manage_Sales_Contact|v23.0
    - 1.1.11.2|Manage_Sales_Lead|v23.0
    - 1.1.11.3|Manage_Sales_Prospect|v23.0
    - 1.1.9|Selling|v23.0
    - 1.1.9.1|Qualify_Selling_Opportunity|v23.0
    - 1.1.9.3|Acquire_Sales_Prospect_Data|v23.0
    - 1.1.7|Market_Sales_Support_&_Readiness|v23.0
    - 1.1.7.2|Support_Selling|v23.0
    - 1.1.7.5|Manage_Sales_Accounts|v23.0
    functionalFrameworkFunctions:
    - 394|Sales_Aids_Support|v23.0
    - 372|Sales_Opportunity_Management|v23.0
    - 375|Funnel_Assigning|v23.0
    - 374|Funnel_Creation|v23.0
    - 376|Funnel_Leads_Tracking|v23.0
    - 726|Sales_Lead_Capturing|v23.0
    SIDs:
    - Market_&_Sales_Domain|Sales_Lead_and_Opportunity_ABE|Sales_Lead_ABE|v25.0
    - Market_&_Sales_Domain|Sales_Lead_and_Opportunity_ABE|Sales_Opportunity_ABE|v25.0
