apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: PaymentManagement
  id: TMFC029
  functionalBlock: PartyManagement
  description: Payment Management manages methods used by parties to make payments,
    it also administers payment plan, handles payment, assigns payments against bills,
    settlements, and other object requiring payments.
  publicationDate: 2024-11-18 00:00:00
  status: specified
  version: 1.2.0
  coreFunction:
    dependentAPIs:
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
    - id: TMF666
      required: false
      resources:
      - partyAccount:
        - GET
        - GET /id
      - billingAccount:
        - GET
        - GET /id
      - settlementAccount:
        - GET
        - GET /id
      - financialAccount:
        - GET
        - GET /id
      - billingCycleSpecification:
        - GET
        - GET /id
      - billFormat:
        - GET
        - GET /id
      - billPresentationMedia:
        - GET
        - GET /id
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddressValidation:
        - GET
        - GET /id
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      version: 4
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
    - id: TMF675
      required: false
      resources:
      - geographicLocation:
        - GET
        - GET /id
      version: 4
    exposedAPIs:
    - id: TMF670
      required: true
      resources:
      - paymentMethod:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
    - id: TMF676
      required: true
      resources:
      - payment:
        - GET
        - GET /id
        - POST
      - refund:
        - GET
        - GET /id
        - POST
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    publishedEvents:
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagement/hub
      implementation: /{{.Release.Name}}-PaymentManagement
      name: PaymentManagement
      port: 80
      resources:
      - PaymentAttributeValueChangeEvent
      - PaymentCreateEvent
      - PaymentDeleteEvent
      - PaymentStatusChangeEvent
      - RefundAttributeValueChangeEvent
      - RefundCreateEvent
      - RefundStatusChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF676_PaymentManagement/master/TMF676-Payment-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentMethods/hub
      implementation: /{{.Release.Name}}-PaymentMethods
      name: PaymentMethods
      port: 80
      resources:
      - PaymentMethodAttributeValueChangeEvent
      - PaymentMethodCreateEvent
      - PaymentMethodDeleteEvent
      - PaymentMethodStatusChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF670_PaymentMethods/master/TMF670-PaymentMethod-v4.0.0.swagger.json
      apiType: openapi
    - hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - ProcessFlowCreateEvent
      - ProcessFlowStateChangeEvent
      - ProcessFlowStateDeleteEvent
      - ProcessFlowStateAttributeValueChangeEvent
      - TaskFlowCreateEvent
      - TaskFlowStateChangeEvent
      - TaskFlowDeleteEvent
      - TaskFlowAttributeValueChangeEvent
      - TaskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents: []
  owners:
  - email: Redacted
    name: Redacted
  maintainers:
  - name: Redacted
    email: components@tmforum.org
