apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
      - version: 4
        resources:
        - individual:
          - GET
          - GET /id
        - organization:
          - GET
          - GET /id
    - id: TMF669
      apiSDO: tmForum
      required: true
      specification:
      - version: 5
        resources:
        - partyRole:
          - POST
      - version: 4
        resources:
        - partyRole:
          - POST
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
        - taskFlow:
          - PATCH
          - GET
          - GET /id
    exposedAPIs:
    - id: TMF720
      apiSDO: tmForum
      required: true
      specification:
      - version: 4
        resources:
        - digitalIdentity:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
        - roles:
          - GET
          - GET /id
          - POST
          - PATCH /id
          - DELETE /id
    - id: TMF701
      apiSDO: tmForum
      required: false
      specification:
      - version: 4
        resources:
        - processFlow:
          - GET
          - GET /id
          - POST
          - DELETE /id
        - taskFlow:
          - GET
          - GET /id
          - PATCH /id
    publishedEvents:
    - implementation: /{{.Release.Name}}-digidemngt
      name: digitalIdentity
      port: 80
      resources:
      - DigitalIdentityCreateEvent
      - DigitalIdentityStateChangeEvent
      - DigitalIdentityDeleteEvent
      - DigitalIdentityAttributeValueChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF720_DigitalIdentityManagement/master/TMF720-DigitalIdentityManagement-v4.0.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - name: PartyRoleManagement
      port: 80
      resources:
      - UserRoleCreationNotification
      - UserRoleChangeNotification
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apiType: openapi
  componentMetadata:
    id: TMFC020
    name: DigitalIdentityManagement
    version: 1.2.0
    description: The Digital Identity Management component is responsible for authentication of parties (customers, employees, partners), and resources authentication.
    publicationDate: 2026-06-08
    status: preview
    functionalBlock: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
    SIDs:
    - Shared_Domain|Digital_Identity_ABE|v25.0
