@startuml
left to right direction

together {

  package "Process" as PkgProcess {
    component "Process" as PRO
  }

  package "Capabilities" as PkgCap {

    component "Capabilities" as CAP
    component "Analytics" as AN
    component "Experiences" as EXP
    component "Data Objects" as DO
    component "Integrations" as INT
    component "Rules" as RULE
    component "Policies" as POL

    CAP --> DO   : implements
    CAP --> EXP  : implements
    CAP --> POL  : implements
    CAP --> RULE : implements
    CAP --> INT  : implements
    CAP --> AN   : implements
  }
}

PRO --> DO  : uses
PRO --> EXP : is exposed by
PRO -->  AN: XXX

' force package placement: Process on the left
PkgProcess -[hidden]-> PkgCap

@enduml