apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: ProductOrderCaptureAndValidation
  id: TMFC002
  functionalBlock: CoreCommerce
  description: Addresses the means of capturing what a customer wants to order, based
    on the CSP Product Catalog. This component permits to choose the configuration
    of the product offerings and products desired, to provide a quote, to check the
    eligibility of the customer order, and to complete it with information needed
    such as the related parties or associated the billing account and the delivery
    appointment if needed. This component is globally in charge of these quote management,
    order capture and validation steps, using dedicated components (e.g., Offering
    Configurator, Service Qualification, Party Mgt) when needed. After the delivery
    of the customer product order items, this component is also in charge of the commercial
    closure of the order. It includes update of the Product Inventory (status and
    starting/end date of tariffs and discounts) and potential commercial rules control
    (e.g. receipt of the contract document signed by the customer)
  publicationDate: 2024-11-12 00:00:00
  status: specified
  version: 2.1.0
  coreFunction:
    dependentAPIs:
    - id: TMF620
      required: true
      resources:
      - productCategory:
        - GET
        - GET /id
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      version: 4
    - id: TMF637
      required: true
      resources:
      - product:
        - GET
        - GET /id
        - POST
        - PATCH
      version: 4
    - id: TMF679
      required: false
      resources:
      - productOfferingQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      version: 4
    - id: TMF645
      required: false
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      - queryServiceQualification:
        - GET
        - GET /id
        - POST
        - PATCH
      version: 4
    - id: TMF646
      required: false
      resources:
      - appointment:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - searchTimeSlot:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      version: 4
    - id: TMF673
      required: false
      resources:
      - geographicAddress:
        - GET
        - GET /id
      - geographicSubAddress:
        - GET
        - GET /id
      - geographicAddressValidation:
        - GET
        - GET /id
        - POST
        - PATCH
      version: 4
    - id: TMF674
      required: false
      resources:
      - geographicSite:
        - GET
        - GET /id
      version: 4
    - id: TMF716
      required: false
      resources:
      - resourceReservation:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - cancelResourceReservation:
        - GET
        - GET /id
        - POST
      version: 4
    - id: TMF687
      required: false
      resources:
      - checkProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - queryProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - reserveProductStock:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - productStock:
        - GET
        - GET /id
      version: 4
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
    - id: TMF669
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      version: 4
    - id: TMF666
      required: false
      resources:
      - billingAccount:
        - GET /id
        - GET
      version: 4
    - id: TMF676
      required: false
      resources:
      - payment:
        - GET / id
        - GET
      version: 4
    - id: TMF683
      required: false
      resources:
      - partyInteraction:
        - GET / id
        - GET
      version: 4
    - id: TMF638
      required: false
      resources:
      - service:
        - GET / id
        - GET
      version: 4
    - id: TMF639
      required: false
      resources:
      - resource:
        - GET / id
        - GET
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - PATCH
        - GET
        - GET /id
      - taskFlow:
        - POST
        - PATCH
        - GET
        - GET /id
      version: 4
    - id: TMF760
      required: false
      resources:
      - checkProductConfiguration:
        - GET
        - GET /id
        - POST
      - queryProductConfiguration:
        - GET
        - GET /id
        - POST        
      version: 5      
    - id: TMF651
      required: false
      resources:
      - agreement:
        - GET
        - GET /id
      version: 4         
    exposedAPIs:
    - id: TMF622
      required: true
      resources:
      - productOrder:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      - cancelProductOrder:
        - POST
        - GET
        - GET /id
      version: 4
    - id: TMF648
      required: false
      resources:
      - quote:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      version: 4
    - id: TMF663
      required: false
      resources:
      - shoppingCart:
        - POST
        - GET
        - GET /id
        - PATCH
        - DELETE
      version: 4
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      version: 4
    publishedEvents:
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/hub
      implementation: /{{.Release.Name}}-ProductOrderEvent
      name: ProductOrder
      port: 80
      resources:
      - productOrderStateChange
      - productOrderCreateEvent
      - productOrderAttributeValueChange
      - productOrderDelete
      - productOrderInformationRequired
      - cancelProductOrderCreateEvent
      - cancelProductOrderStateChange
      - cancelProductOrderInformationRequired
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Quote/hub
      implementation: /{{.Release.Name}}-QuoteEvent
      name: Quote
      port: 80
      resources:
      - quoteStateChange
      - quoteCreateEvent
      - quoteAttributeValueChange
      - quoteDelete
      - quoteInformationRequired
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ShoppingCart/hub
      implementation: /{{.Release.Name}}-ShoppingCartEvent
      name: ShoppingCart
      port: 80
      resources:
      - shoppingCartCreateEvent
      - shoppingCartAttributeValueChange
      - shoppingCartDelete
      specification: https://github.com/tmforum-apis/TMF663_ShoppingCart/blob/master/TMF663-ShoppingCart-v4.0.0.swagger.json
    - apiType: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      resources:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      apiType: openapi
    subscribedEvents:
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualification/call-back
      implementation: /{{.Release.Name}}-ProductOfferingQualificationEvent
      name: ProductOfferingQualification
      port: 80
      resources:
      - productOfferingQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF679_ProductOfferingQualification/blob/master/TMF679-ProductOfferingQualification-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualification/call-back
      implementation: /{{.Release.Name}}-ServiceQualificationEvent
      name: ServiceQualification
      port: 80
      resources:
      - checkServiceQualificationStateChangeEvent
      - queryServiceQualificationStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF645_ServiceQualification/blob/master/TMF645-ServiceQualification-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/call-back
      implementation: /{{.Release.Name}}-GeographicAddressManagementEvent
      name: GeographicAddressManagement
      port: 80
      resources:
      - geographicAddressValidationStateChange
      specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagementEvent/call-back
      implementation: /{{.Release.Name}}-PaymentManagementEvent
      name: PaymentManagement
      port: 80
      resources:
      - paymentCreate
      - paymentStateChange
      specification: https://github.com/tmforum-apis/TMF676_PaymentManagement/blob/master/TMF676-Payment-v4.0.0.swagger.json
    - apiType: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceReservationEvent/call-back
      implementation: /{{.Release.Name}}-ResourceReservationEvent     
      name: ResourceReservation
      port: 80
      resources:
      - resourceReservationCreateEvent
      - resourceReservationAttributeValueChangeEvent
      - resourceReservationDeleteEvent
      - resourceReservationStateChangeEvent
      - resourceReservationInformationRequiredEvent
      - cancelResourceReservationCreateEvent
      - cancelResourceReservationStateChangeEvent
      - cancelResourceReservationInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF716_ResourceReservation/blob/master/TMF716-ResourceReservation-v4.1.0.swagger.json
  owners:
  - email: Redacted
    name: Redacted
  maintainers:
  - name: Redacted
    email: components@tmforum.org
  eTOMs:
  - 1.1.9_Selling_v23.0
  - 1.1.9.2_Develop_Sales_Proposal_v23.0
  - 1.1.9.5_Negotiate_Sales/Contract_v23.0
  - 1.2.9_Product_Offering_Purchasing_v23.0
  - 1.3.3_Customer_Order_Handling_v23.0
  - 1.3.3.1_Determine_Customer_Order_Feasibility_v23.0
  - 1.3.3.2_Authorize_Credit_v23.0
  - 1.3.3.4_Complete_Customer_Order_v23.0
  - 1.3.3.5_Issue_Customer_Orders_v23.0
  - 1.3.3.6_Report_Customer_Order_Handling_v23.0
  - 1.3.3.7_Close_Customer_Order_v23.0
  - 1.3.3.8_Manage_Order_Fallout_v23.0
  functionalFrameworkFunctions:
  - 16_Fallout_Automated_Correction_v23.0
  - 17_Fallout_Correction_Information_Collection_v23.0
  - 18_Fallout_Management_to_Fulfillment_Application_Accessing_v23.0
  - 19_Fallout_Manual_Correction_Queuing_v23.0
  - 20_Fallout_Notification_v23.0
  - 21_Fallout_Orchestration_v23.0
  - 22_Fallout_Reporting_v23.0
  - 23_Fallout_Dashboard_System_Log-in_Accessing_v23.0
  - 24_Pre-populated_Fallout_Information_Presentation_v23.0
  - 120_Customer_Order_Capturing_v23.0
  - 172_Customer_Order_Reporting_v23.0
  - 174_Customer_Order_Error_Resolution_Support_v23.0
  - 176_Customer_Order_Capturing_Access_v23.0
  - 177_Customer_Order_Take-over_Management_v23.0
  - 178_Customer_Order_Administration_v23.0
  - 181_Product_Order_Data_Collection_v23.0
  - 204_Customer_Order_Completion_v23.0
  - 205_Customer_Order_Eligibility_Validation_v23.0
  - 208_Customer_Order_Change_Management_v23.0
  - 209_Customer_Order_Cancellation_v23.0
  - 211_Customer_Order_Activity_Supervision_v23.0
  - 212_Customer_Order_Versioning_v23.0
  - 213_Pending_Customer_Orders_Maintenance_v23.0
  - 217_Customer_Order_Establishment_Tracking_v23.0
  - 236_Customer_Loyalty_Subscription_Management_v23.0
  - 259_External_Call_Center_Access_v23.0
  - 272_Order_Status_Viewing_v23.0
  - 277_Shopping_Cart_Purchasing_Access_v23.0
  - 317_Product_Availability_Area_Checking_v23.0
  - 343_Mass_Transaction_Ordering_v23.0
  - 359_Contract_and_SLA_creation_v23.0
  - 366_Customer_Order_Management_v23.0
  - 379_Product_Customization_Offering_Management_v23.0
  - 387_Sales_Metrics_Calculation_v23.0
  - 388_Sales_Order_Reporting_v23.0
  - 716_Order_Data_Enrichment_v23.0
  - 717_Calculated_Order_Data_Enrichment_v23.0
  - 718_Customer_Order_Validation_v23.0
  - 719_Customer_Order_Storage_v23.0
  - 720_Customer_Order_Searching_v23.0
  - 756_Fallout_Rule_Based_Error_Correction_v23.0
  - 934_Sales_Negotiation_Support_v23.0
  - 1063_Sales_Quote_Management_v23.0