apiVersion: oda.tmforum.org/v1beta3
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  name: BillCalculation
  id: TMFC031
  functionalBlock: PartyManagement
  description: Bill generation mgmt. manage the party invoice management. It addresses
    the invoice formatting, presentation and dispatching to the proper means of communication.
  publicationDate: 2023-06-25
  status: specified
  version: 2.0.0
  coreFunction:
    dependentAPIs:
    - id: TMF666
      required: true
      resources:
      - BillingAccount:
        - GET
        - GET /id
      - BillingCycleSpecification:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF637
      required: true
      resources:
      - product:
        - GET
        - GET /id
      version: 4.0
      name: _must_be_defined
      apiType: openapi
    - id: TMF620
      required: false
      resources:
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      version: 4.0
      name: _must_be_defined
      apiType: openapi
    - id: TMF635
      required: false
      resources:
      - usage:
        - GET
        - GET /id
      - usageSpecification:
        - GET
        - GET /id
      version: 4.0
      name: _must_be_defined
      apiType: openapi
    exposedAPIs:
    - id: TMF678
      required: true
      resources:
      - appliedCustomerBillingRate:
        - GET
        - GET /id
      version: 4
      name: _must_be_defined
      apiType: openapi
      implementation: _must_be_defined
      path: _must_be_defined
      port: 80
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      version: 4
      name: _must_be_defined
      apiType: openapi
      implementation: _must_be_defined
      path: _must_be_defined
      port: 80
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  eventNotification:
    publishedEvents: []
    subscribedEvents:
    - name: usageManagement
      port: 80
      resources:
      - UsageCreateEvent
      - UsageAttributeValueChangeEvent
      - UsageDeleteEvent
      - UsageStateChangeEvent
      - UsageSpecificationCreateEvent
      - UsageSpecificationAttributeValueChangeEvent
      - UsageSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635-UsageManagement-v4.0.0.swagger.json
      id: TMF635
