apiVersion: oda.tmforum.org/v1beta4
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF666
      required: true
      resources:
      - BillingAccount:
        - GET
        - GET /id
      - BillingCycleSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF632
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF637
      required: true
      resources:
      - product:
        - GET
        - GET /id
      version: 4.0
      apiSDO: tmForum
    - id: TMF620
      required: false
      resources:
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - PATCH
      version: 4.0
      apiSDO: tmForum
    - id: TMF635
      required: false
      resources:
      - usage:
        - GET
        - GET /id
      - usageSpecification:
        - GET
        - GET /id
      version: 4.0
      apiSDO: tmForum
    exposedAPIs:
    - id: TMF678
      required: true
      resources:
      - appliedCustomerBillingRate:
        - GET
        - GET /id
      version: 4
      apiSDO: tmForum
    - id: TMF701
      required: false
      resources:
      - processFlow:
        - GET
        - GET /id
        - POST
        - DELETE /id
      - taskFlow:
        - GET
        - GET /id
        - PATCH /id
      version: 4
      apiSDO: tmForum
    publishedEvents: []
    subscribedEvents:
    - name: usageManagement
      port: 80
      resources:
      - UsageCreateEvent
      - UsageAttributeValueChangeEvent
      - UsageDeleteEvent
      - UsageStateChangeEvent
      - UsageSpecificationCreateEvent
      - UsageSpecificationAttributeValueChangeEvent
      - UsageSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF635_UsageManagement/blob/master/TMF635-UsageManagement-v4.0.0.swagger.json
  componentMetadata:
    id: TMFC031
    name: BillCalculation
    version: 2.0.0
    description: Bill generation mgmt. manage the party invoice management. It addresses
      the invoice formatting, presentation and dispatching to the proper means of
      communication.
    publicationDate: 2023-06-25
    status: specified
    functionalBlock: PartyManagement
    owners:
    - email: Redacted
      name: Redacted
      url: Redacted
    maintainers:
    - name: Redacted
      email: components@tmforum.org
      url: Redacted
    eTOMs: []
    functionalFrameworkFunctions: []
