name: Trigger Tests
run-name: Component validation checks
on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Branch name'
        required: true
        default: 'v1beta2'

  pull_request:
    branches:
      - v1beta*
    paths:
      - 'specifications/*'

jobs:
  spec-test-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Components
        uses: actions/checkout@v4
      - name: install dependencies
        run: pip3 install -r .github/ci/requirements.txt 
      
      - name: Validate component schema
        run: |
          python3 ci/validateComponents.py 
      
