name: Trigger Tests
on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Branch name'
        required: true
        default: 'v1beta2'

  pull_request:
    branches:
      - v1beta2


jobs:
  calcualte-changes:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.calculate-changes.outputs.components }}
    steps:
      - name: Checkout Components
        uses: actions/checkout@v4
      - name: Calculate Changes
        run: | 
          python3 .github/ci/calculate_changes.py >> $GITHUB_OUTPUT
