name: Trigger Tests
on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Branch name'
        required: true
        default: 'v1beta2'

  pull_request:
    branches:
      - v1beta*

jobs:
  calcualte-changes:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.calculate-changes.outputs.components }}
    steps:
      - name: Checkout Components
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate Changes
        run: |
          git fetch origin
          git diff --name-only --diff-filter=M HEAD origin/${{ github.base_ref }} >> filechanges

          pip3 install -r .github/ci/requirements.txt 
          python3 .github/ci/calculate_changes.py "$GITHUB_OUTPUT"
  spec-test-matrix:
    runs-on: ubuntu-latest
    needs: calcualte-changes
    strategy:
        matrix:
            component: ${{fromJson(needs.calcualte-changes.outputs.components)}}
        fail-fast: false
    steps:
      - name: Checkout Components
        uses: actions/checkout@v4
      
