name: Trigger build

on: [push]

jobs:
  trigger_target:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target workflow
        env: 
          BRANCH_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.DEVOPS_TOKEN }}
        run: |
          echo $BRANCH_NAME
          curl -X POST \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/tmforum-rand/TMForum-ODA-Asset-Build/actions/workflows/72084960/dispatches \
          -d "{\"ref\":\"main\", \"inputs\": {\"ref_name\":\"$BRANCH_NAME\"}}"
